import { generateTrainingDraftCore } from "@/lib/training-architect.server";

type EventName="user.created"|"onboarding.completed"|"plan.activated"|"payment.confirmed"|"photo_protocol.completed"|"assessment.generated"|"assessment.approved"|"cycle.draft_created"|"training.ready_for_generation"|"training.draft_generated"|"training.approved"|"training.published"|"nutrition.created"|"nutrition.published"|"protocol.published"|"perception.completed"|"checkin.completed"|"weekly_review.completed"|"reassessment.due";

function deliveryTarget(){const date=new Date();let days=0;while(days<3){date.setUTCDate(date.getUTCDate()+1);const day=date.getUTCDay();if(day!==0&&day!==6)days+=1;}date.setUTCHours(20,59,59,999);return date.toISOString()}
async function activeStaff(admin:any, roles:string[]){const {data}=await admin.from("user_roles").select("user_id,role").in("role",roles);return (data??[]).map((row:any)=>row.user_id as string)}
async function task(admin:any,input:{key:string;title:string;clientId:string;actorId:string;assigneeId?:string|null;priority?:string;description?:string}){await admin.from("admin_tasks").upsert({operation_key:input.key,title:input.title,client_id:input.clientId,created_by:input.actorId,assignee_id:input.assigneeId??input.actorId,priority:input.priority??"high",status:"todo",description:input.description??null},{onConflict:"operation_key",ignoreDuplicates:true})}
async function notify(admin:any,input:{key:string;clientId:string;recipients:string[];type:string;title:string;message:string;path:string}){if(!input.recipients.length)return;await admin.from("admin_notifications").upsert(input.recipients.map(recipient_id=>({recipient_id,client_id:input.clientId,operation_key:input.key,notification_type:input.type,title:input.title,message:input.message,target_path:input.path})),{onConflict:"recipient_id,operation_key",ignoreDuplicates:true})}
async function operationEvent(admin:any,input:{clientId:string;activationId?:string|null;event:string;actor:"CLIENT"|"BRUNO"|"TEAM"|"SYSTEM";summary:string;metadata?:Record<string,unknown>}){await admin.from("client_operation_events").insert({client_id:input.clientId,activation_id:input.activationId??null,event_type:input.event,actor_type:input.actor,summary:input.summary,metadata:input.metadata??{}})}

export async function evaluateTrainingReadinessCore(admin:any,clientId:string){
  const [profile,onboarding,score,assessment,photos,cycle,library,pain]=await Promise.all([
    admin.from("profiles").select("onboarding_completed_at").eq("id",clientId).single(),admin.from("onboarding_responses").select("completed_at").eq("user_id",clientId).maybeSingle(),admin.from("sim_scores").select("id").eq("user_id",clientId).limit(1).maybeSingle(),admin.from("assessments").select("id,status,approved_at").eq("client_id",clientId).order("created_at",{ascending:false}).limit(1).maybeSingle(),admin.from("assessment_photos").select("id,slot_id").eq("client_id",clientId),admin.from("cycle_strategies").select("id,status").eq("client_id",clientId).in("status",["draft","active"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),admin.from("exercise_library").select("id",{count:"exact",head:true}).eq("active",true),admin.from("pain_reports").select("id").eq("user_id",clientId).eq("classification","RED").neq("status","closed")]);
  const result={onboarding:Boolean(profile.data?.onboarding_completed_at||onboarding.data?.completed_at),baseline:Boolean(score.data),photo_protocol:new Set((photos.data??[]).map((x:any)=>x.slot_id)).size>=17,assessment:Boolean(assessment.data?.approved_at||assessment.data?.status==="approved"),cycle:Boolean(cycle.data),exercise_library_available:(library.count??0)>0,health_flags:(pain.data??[]).length>0};
  const missing=Object.entries(result).filter(([key,value])=>key==="health_flags"?value:!value).map(([key])=>key);
  return {...result,ready:missing.length===0,missing,cycleId:cycle.data?.id??null,assessmentStatus:assessment.data?.status??null};
}

async function ensureCycle(admin:any,clientId:string,actorId:string){const {data:existing}=await admin.from("cycle_strategies").select("id").eq("client_id",clientId).in("status",["draft","active"]).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existing)return existing.id;const {data:onboarding}=await admin.from("onboarding_responses").select("responses").eq("user_id",clientId).maybeSingle();const answers=(onboarding?.responses??{}) as Record<string,unknown>;const {data:created,error}=await admin.from("cycle_strategies").insert({client_id:clientId,start_date:new Date().toISOString().slice(0,10),visual_goal:String(answers['main_goal']??"Construção inicial"),structural_goal:"Estabelecer base de movimento",capacity_goal:"Sustentar execução",behavior_goal:"Construir consistência",weekly_frequency:Number(answers['sustainable_training_days']??3),session_duration:Number(answers['session_minutes']??50),strategy_summary:"Estratégia inicial aguardando revisão humana.",created_by:actorId,status:"draft"}).select("id").single();if(error||!created)throw error??new Error("Não foi possível criar o ciclo.");return created.id}

export async function orchestrateClientEvent(input:{admin:any;clientId:string;event:EventName;actorId:string;metadata?:Record<string,unknown>}){
  const {admin,clientId,event,actorId}=input;const {data:profile}=await admin.from("profiles").select("first_name,last_name,plan,onboarding_completed_at").eq("id",clientId).single();if(!profile)throw new Error("Cliente não encontrado.");
  const paid=profile.plan!=="free";if(!paid&&event!=="user.created"&&event!=="onboarding.completed")return null;
  const readiness=await evaluateTrainingReadinessCore(admin,clientId);const {data:protocol}=await admin.from("protocols").select("id,status").eq("user_id",clientId).order("created_at",{ascending:false}).limit(1).maybeSingle();const {data:program}=await admin.from("workout_programs").select("id,status").eq("user_id",clientId).order("created_at",{ascending:false}).limit(1).maybeSingle();const {data:nutrition}=await admin.from("nutrition_plans").select("id,status").eq("user_id",clientId).order("created_at",{ascending:false}).limit(1).maybeSingle();
  let stage:any="ONBOARDING_REQUIRED";let nextAction="Complete sua calibração inicial";let owner="CLIENT";let status:any="BLOCKED";
  if(readiness.onboarding&&!readiness.baseline){stage="BASELINE_REQUIRED";nextAction="Conclua seu diagnóstico de performance"}
  else if(readiness.onboarding&&readiness.baseline&&!readiness.photo_protocol){stage="PHOTO_PROTOCOL_REQUIRED";nextAction="Precisamos das suas fotos para continuar"}
  else if(readiness.photo_protocol&&!readiness.assessment){stage=readiness.assessmentStatus==="ready_for_review"?"ASSESSMENT_REVIEW":"ASSESSMENT_PROCESSING";nextAction=readiness.assessmentStatus==="ready_for_review"?"Revisar avaliação fotográfica":"Sua avaliação está sendo preparada";owner=readiness.assessmentStatus==="ready_for_review"?"BRUNO":"SYSTEM"}
  else if(readiness.assessment&&!readiness.cycle){stage="CYCLE_STRATEGY";nextAction="Construindo sua estratégia";owner="SYSTEM";status="ACTIVE"}
  else if(program?.status==="draft"){stage="TRAINING_REVIEW";nextAction="Seu treinamento está em revisão pela equipe";owner="BRUNO";status="ACTIVE"}
  else if(!program||program.status!=="published"){stage="TRAINING_GENERATION";nextAction="Nossa inteligência está construindo sua estratégia";owner="SYSTEM";status="ACTIVE"}
  else if(!nutrition||nutrition.status!=="published"){stage="NUTRITION_BUILD";nextAction="Sua orientação nutricional está em construção";owner="TEAM";status="ACTIVE"}
  else if(protocol?.status!=="published"){stage="READY_TO_PUBLISH";nextAction="Revisar e liberar protocolo executivo";owner="BRUNO";status="READY"}
  else{stage="ACTIVE_PROTOCOL";nextAction="Começar treino";owner="CLIENT";status="COMPLETED"}
  const {data:existingActivation}=await admin.from("client_activations").select("current_stage,stage_started_at,target_delivery_at").eq("client_id",clientId).maybeSingle();
  const stageChanged=existingActivation?.current_stage!==stage;
  const {data:activation}=await admin.from("client_activations").upsert({client_id:clientId,plan:profile.plan,status,current_stage:stage,source:String(input.metadata?.['source']??"system"),payment_reference:typeof input.metadata?.['paymentReference']==="string"?input.metadata['paymentReference']:null,responsible_id:actorId,next_action:nextAction,next_action_owner:owner,target_delivery_at:stageChanged||!existingActivation?.target_delivery_at?deliveryTarget():existingActivation.target_delivery_at,stage_started_at:stageChanged||!existingActivation?.stage_started_at?new Date().toISOString():existingActivation.stage_started_at,completed_at:status==="COMPLETED"?new Date().toISOString():null,metadata:{last_event:event,readiness}},{onConflict:"client_id"}).select("id").single();
  if(!activation)return null;
  await operationEvent(admin,{clientId,activationId:activation.id,event,actor:owner==="CLIENT"?"CLIENT":owner==="BRUNO"?"BRUNO":owner==="TEAM"?"TEAM":"SYSTEM",summary:`${event.replaceAll("."," ")} · ${stage.replaceAll("_"," ")}`,metadata:{stage,next_action:nextAction}});
  const {data:job}=await admin.from("training_generation_jobs").select("*").eq("client_id",clientId).in("status",["WAITING_PREREQUISITES","READY","GENERATING","DRAFT_READY","HUMAN_REVIEW","APPROVED"]).order("created_at",{ascending:false}).limit(1).maybeSingle();
  const jobStatus=readiness.ready?(job?.status??"READY"):"WAITING_PREREQUISITES";const jobValues={client_id:clientId,activation_id:activation.id,cycle_id:readiness.cycleId,status:jobStatus,trigger_source:event,missing_prerequisites:readiness.missing,readiness_snapshot:readiness};
  if(job)await admin.from("training_generation_jobs").update(jobValues).eq("id",job.id);else await admin.from("training_generation_jobs").insert(jobValues);
  return {activation,readiness,jobId:job?.id??null};
}

export async function activateClientPlanCore(input:{admin:any;clientId:string;plan:"free"|"paid"|"plus"|"premium";source:"manual_admin"|"payment"|"migration"|"system";paymentReference?:string;actorId:string}){
  const {admin,clientId,plan,source,actorId}=input;const {data:before}=await admin.from("profiles").select("plan,first_name,last_name").eq("id",clientId).single();if(!before)throw new Error("Cliente não encontrado.");
  const {error:transactionError}=await admin.rpc("activate_client_plan_transaction",{_client_id:clientId,_plan:plan,_source:source,_actor_id:actorId,_payment_reference:input.paymentReference??null});if(transactionError)throw transactionError;
  if(plan==="free"){await admin.from("client_activations").update({status:"CANCELLED",completed_at:new Date().toISOString(),plan}).eq("client_id",clientId);return {plan,activation:null}}
  const {data:protocol}=await admin.from("protocols").select("id").eq("user_id",clientId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!protocol)await admin.from("protocols").insert({user_id:clientId,title:"Protocolo executivo",objective:"Construção de performance executiva",status:"data_received",created_by:actorId});
  const {data:assignment}=await admin.from("client_assignments").select("staff_id").eq("client_id",clientId).eq("assignment_role","primary").eq("active",true).limit(1).maybeSingle();const responsible=assignment?.staff_id??actorId;if(!assignment)await admin.from("client_assignments").upsert({client_id:clientId,staff_id:responsible,assignment_role:"primary",active:true,assigned_by:actorId},{onConflict:"client_id,staff_id,assignment_role",ignoreDuplicates:true});
  await admin.from("client_relationships").upsert({client_id:clientId,journey_phase:"ACTIVATION",relationship_state:"COMMITTED",attention_level:"NORMAL",responsible_user:responsible,next_action:"Acompanhar ativação do protocolo",next_action_due_at:deliveryTarget()},{onConflict:"client_id"});
  const name=[before.first_name,before.last_name].filter(Boolean).join(" ")||"cliente";await task(admin,{key:`activation:${clientId}`,title:`Acompanhar ativação — ${name}`,clientId,actorId,assigneeId:responsible,priority:plan==="premium"?"critical":"high"});await task(admin,{key:`nutrition-build:${clientId}`,title:`Construir nutrição — ${name}`,clientId,actorId,assigneeId:responsible,priority:"high",description:"Orientação manual aguardando metodologia nutricional oficial."});
  const metadata:Record<string,unknown>={source};if(input.paymentReference)metadata['paymentReference']=input.paymentReference;const result=await orchestrateClientEvent({admin,clientId,event:"plan.activated",actorId,metadata});const staff=await activeStaff(admin,["admin_master","coach","manager"]);await notify(admin,{key:`plan-activated:${clientId}`,clientId,recipients:staff,type:"PLAN_ACTIVATED",title:`Plano ativado — ${name}`,message:`${plan.toUpperCase()} entrou na fila de entrega.`,path:`/admin/students/${clientId}`});return {plan,activation:result?.activation??null};
}

export async function processTrainingGeneration(input:{admin:any;clientId:string;actorId:string;force?:boolean}){
  const readiness=await evaluateTrainingReadinessCore(input.admin,input.clientId);let cycleId=readiness.cycleId;if(readiness.assessment&&!cycleId)cycleId=await ensureCycle(input.admin,input.clientId,input.actorId);const reevaluated=await evaluateTrainingReadinessCore(input.admin,input.clientId);const {data:job}=await input.admin.from("training_generation_jobs").select("*").eq("client_id",input.clientId).in("status",["WAITING_PREREQUISITES","READY","GENERATING","FAILED","DRAFT_READY","HUMAN_REVIEW"]).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!reevaluated.ready||!cycleId){if(job)await input.admin.from("training_generation_jobs").update({status:"WAITING_PREREQUISITES",missing_prerequisites:reevaluated.missing,readiness_snapshot:reevaluated}).eq("id",job.id);return {generated:false,readiness:reevaluated}}
  if(job&&["DRAFT_READY","HUMAN_REVIEW"].includes(job.status)&&!input.force)return {generated:false,readiness:reevaluated,programId:job.program_id};const jobId=job?.id;const now=new Date().toISOString();let currentJobId=jobId;if(jobId)await input.admin.from("training_generation_jobs").update({status:"GENERATING",attempts:(job.attempts??0)+1,started_at:now,error_message:null,cycle_id:cycleId}).eq("id",jobId);else{const {data:created}=await input.admin.from("training_generation_jobs").insert({client_id:input.clientId,cycle_id:cycleId,status:"GENERATING",trigger_source:"training.ready_for_generation",attempts:1,started_at:now,missing_prerequisites:[],readiness_snapshot:reevaluated}).select("id").single();currentJobId=created?.id}
  try{const generated=await generateTrainingDraftCore({clientId:input.clientId,cycleId,actorId:input.actorId,admin:input.admin});if(currentJobId)await input.admin.from("training_generation_jobs").update({status:"DRAFT_READY",program_id:generated.programId,finished_at:new Date().toISOString()}).eq("id",currentJobId);const {data:profile}=await input.admin.from("profiles").select("first_name,last_name").eq("id",input.clientId).single();const name=[profile?.first_name,profile?.last_name].filter(Boolean).join(" ")||"cliente";await task(input.admin,{key:`training-review:${generated.programId}`,title:`Revisar treino — ${name}`,clientId:input.clientId,actorId:input.actorId,priority:"high",description:"AI Draft pronto para edição, aprovação humana e publicação."});const staff=await activeStaff(input.admin,["admin_master","coach"]);await notify(input.admin,{key:`training-review:${generated.programId}`,clientId:input.clientId,recipients:staff,type:"TRAINING_IN_REVIEW",title:`Revisar treino — ${name}`,message:"A Training Intelligence concluiu o draft.",path:`/admin/training/${input.clientId}`});await input.admin.from("crm_events").insert({user_id:input.clientId,event_type:"training.draft_generated",metadata:{program_id:generated.programId,job_id:currentJobId}});await orchestrateClientEvent({admin:input.admin,clientId:input.clientId,event:"training.draft_generated",actorId:input.actorId});return {generated:true,readiness:reevaluated,programId:generated.programId}}
  catch(error){const message=error instanceof Error?error.message:"Falha na geração";const needsLibrary=message.startsWith("NEEDS_LIBRARY:");if(currentJobId)await input.admin.from("training_generation_jobs").update({status:needsLibrary?"NEEDS_LIBRARY":"FAILED",finished_at:new Date().toISOString(),error_code:needsLibrary?"NEEDS_LIBRARY":"GENERATION_FAILED",error_message:message,last_error:message,last_attempt_at:new Date().toISOString()}).eq("id",currentJobId);await task(input.admin,{key:`training-error:${currentJobId??input.clientId}`,title:needsLibrary?`Biblioteca precisa de exercício — ${message.replace("NEEDS_LIBRARY:","")}`:"Falha na geração de treino",clientId:input.clientId,actorId:input.actorId,priority:"critical",description:message});throw error}
}

export async function processClientActivation(input:{admin:any;clientId:string;actorId:string;event:EventName}){
  const state=await orchestrateClientEvent(input);
  if(!state)return null;
  let readiness=state.readiness;
  if(readiness.assessment&&!readiness.cycle){await ensureCycle(input.admin,input.clientId,input.actorId);readiness=await evaluateTrainingReadinessCore(input.admin,input.clientId);await operationEvent(input.admin,{clientId:input.clientId,activationId:state.activation.id,event:"cycle.draft_created",actor:"SYSTEM",summary:"Cycle Strategy draft criado automaticamente"});}
  const {data:existingProgram}=await input.admin.from("workout_programs").select("id,status").eq("user_id",input.clientId).in("status",["draft","approved","published"]).order("created_at",{ascending:false}).limit(1).maybeSingle();
  if(readiness.ready&&!existingProgram){try{await processTrainingGeneration({admin:input.admin,clientId:input.clientId,actorId:input.actorId})}catch{/* A falha já foi persistida e ficará visível na Produção. */}}
  const nutritionReady=readiness.onboarding&&readiness.baseline;
  const {data:nutrition}=await input.admin.from("nutrition_plans").select("id,status").eq("user_id",input.clientId).order("created_at",{ascending:false}).limit(1).maybeSingle();
  const nutritionStatus=nutrition?.status==="published"?"PUBLISHED":nutrition?.status==="review"?"HUMAN_REVIEW":nutrition?.status==="draft"?"DRAFT_READY":nutritionReady?"READY":"WAITING_DATA";
  await input.admin.from("nutrition_generation_jobs").upsert({client_id:input.clientId,activation_id:state.activation.id,status:nutritionStatus,trigger_source:input.event,missing_prerequisites:nutritionReady?[]:["onboarding","baseline"],readiness_snapshot:{onboarding:readiness.onboarding,baseline:readiness.baseline},plan_id:nutrition?.id??null},{onConflict:"client_id",ignoreDuplicates:false});
  return {...state,readiness};
}
