import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

async function requireOperator(context:{supabase:any;userId:string}){const{data}=await context.supabase.from("user_roles").select("role").eq("user_id",context.userId);if(!data?.some((row:{role:string})=>["coach","manager","admin","admin_master","nutritionist","nutrition","specialist"].includes(row.role)))throw new Error("Acesso restrito à equipe operacional.")}

export const activateClientPlan=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({clientId:z.string().uuid(),plan:z.enum(["free","paid","plus","premium"]),source:z.enum(["manual_admin","payment","migration","system"]).default("manual_admin"),paymentReference:z.string().max(180).optional()}).parse(input)).handler(async({data,context})=>{await requireOperator(context);const{trustedAdmin}=await import("@/lib/trusted-admin.server");const{activateClientPlanCore}=await import("@/lib/sim-orchestrator.server");return activateClientPlanCore({admin:trustedAdmin,clientId:data.clientId,plan:data.plan,source:data.source,...(data.paymentReference?{paymentReference:data.paymentReference}:{}),actorId:context.userId})});

export const refreshClientOperations=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({clientId:z.string().uuid(),event:z.enum(["onboarding.completed","photo_protocol.completed","assessment.generated","assessment.approved","cycle.draft_created","training.ready_for_generation","training.approved","training.published","nutrition.created","nutrition.published","protocol.published","perception.completed","checkin.completed","weekly_review.completed","reassessment.due"])}).parse(input)).handler(async({data,context})=>{const self=data.clientId===context.userId;if(!self)await requireOperator(context);const{trustedAdmin}=await import("@/lib/trusted-admin.server");const{processClientActivation}=await import("@/lib/sim-orchestrator.server");return processClientActivation({admin:trustedAdmin,clientId:data.clientId,event:data.event,actorId:context.userId})});

export const approveAssessmentAndGenerate=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({clientId:z.string().uuid(),assessmentId:z.string().uuid()}).parse(input)).handler(async({data,context})=>{await requireOperator(context);const{trustedAdmin}=await import("@/lib/trusted-admin.server");const{error}=await trustedAdmin.from("assessments").update({status:"approved",approved_by:context.userId,approved_at:new Date().toISOString()}).eq("id",data.assessmentId).eq("client_id",data.clientId);if(error)throw error;const{processClientActivation}=await import("@/lib/sim-orchestrator.server");return processClientActivation({admin:trustedAdmin,clientId:data.clientId,event:"assessment.approved",actorId:context.userId})});

export const runTrainingGeneration=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({clientId:z.string().uuid(),force:z.boolean().optional()}).parse(input)).handler(async({data,context})=>{await requireOperator(context);const{trustedAdmin}=await import("@/lib/trusted-admin.server");const{processTrainingGeneration}=await import("@/lib/sim-orchestrator.server");return processTrainingGeneration({admin:trustedAdmin,clientId:data.clientId,actorId:context.userId,...(data.force===undefined?{}:{force:data.force})})});

export const transitionTrainingProgram=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((input:unknown)=>z.object({clientId:z.string().uuid(),programId:z.string().uuid(),status:z.enum(["approved","published","archived"])}).parse(input)).handler(async({data,context})=>{await requireOperator(context);const{trustedAdmin}=await import("@/lib/trusted-admin.server");const{data:program}=await trustedAdmin.from("workout_programs").select("id,cycle_id,approved_at").eq("id",data.programId).eq("user_id",data.clientId).single();if(!program)throw new Error("Programa não encontrado.");if(data.status==="published"&&!program.approved_at)throw new Error("Aprovação humana obrigatória antes da publicação.");const now=new Date().toISOString();const changes=data.status==="approved"?{status:"approved",approved_by:context.userId,approved_at:now}:data.status==="published"?{status:"published",published_at:now}:{status:"archived",rejected_at:now};const{error}=await trustedAdmin.from("workout_programs").update(changes).eq("id",program.id);if(error)throw error;const jobStatus=data.status==="approved"?"APPROVED":data.status==="published"?"PUBLISHED":"FAILED";await trustedAdmin.from("training_generation_jobs").update({status:jobStatus,finished_at:new Date().toISOString(),error_message:data.status==="archived"?"Draft rejeitado em revisão humana.":null}).eq("program_id",program.id);await trustedAdmin.from("training_decisions").insert({client_id:data.clientId,cycle_id:program.cycle_id,program_id:program.id,decision_type:`TRAINING_${data.status.toUpperCase()}`,decision:`Programa ${data.status}`,reason:"Revisão humana registrada no cockpit.",author_type:"BRUNO",author_id:context.userId,approval_status:data.status==="approved"?"approved":"pending"});if(data.status!=="archived"){const event=data.status==="approved"?"training.approved":"training.published";await trustedAdmin.from("crm_events").insert({user_id:data.clientId,event_type:event,metadata:{program_id:program.id}});const{orchestrateClientEvent}=await import("@/lib/sim-orchestrator.server");await orchestrateClientEvent({admin:trustedAdmin,clientId:data.clientId,event,actorId:context.userId})}return{ok:true}});
