import { useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { z } from "zod";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Brand } from "@/components/sim/Brand";

export const Route = createFileRoute("/auth")({ head:()=>({meta:[{title:"Acesso — Shape Is Money OS"},{name:"description",content:"Acesse sua carteira de performance executiva."},{property:"og:title",content:"Acesso — Shape Is Money OS"},{property:"og:description",content:"Governe o corpo. Sustente a vida."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: AuthPage });
const schema=z.object({email:z.string().email("Informe um email válido").max(255),password:z.string().min(8,"Use ao menos 8 caracteres").max(72)});
function AuthPage(){const [signup,setSignup]=useState(false);const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const navigate=useNavigate();
  async function submit(e:React.FormEvent){e.preventDefault();const parsed=schema.safeParse({email,password});if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Revise os dados.");return}setBusy(true);setMessage("");if(signup){const [first_name,...rest]=name.trim().split(/\s+/);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin, data:{first_name:first_name??"",last_name:rest.join(" ")}}});setMessage(error?.message??(data.session?"Conta criada.":"Confirme seu email para ativar o acesso."));if(data.session)await navigate({to:"/onboarding"});}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage("Não foi possível entrar. Verifique suas credenciais.");else await navigate({to:"/dashboard"});}setBusy(false)}
  async function google(){const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error)setMessage("Não foi possível continuar com Google.");}
  return <main className="grid min-h-screen lg:grid-cols-[1.1fr_.9fr]"><section className="relative hidden overflow-hidden border-r border-border p-14 lg:flex lg:flex-col lg:justify-between"><Brand/><div className="absolute left-1/2 top-1/2 -z-0 h-[560px] w-[420px] -translate-x-1/2 -translate-y-1/2 rounded-t-full border border-primary/40 bg-card shadow-2xl"/><div className="relative z-10 max-w-xl"><p className="sim-kicker">Executive wellness</p><h1 className="mt-6 text-6xl leading-tight">O corpo é o primeiro ativo de reputação.</h1></div><p className="relative z-10 text-xs uppercase tracking-[0.2em] text-muted-foreground">Disciplina · Presença · Reputação · Liberdade</p></section><section className="flex items-center justify-center px-5 py-12"><div className="w-full max-w-md"><div className="mb-12 lg:hidden"><Brand/></div><p className="sim-kicker">Acesso privado</p><h2 className="mt-4 text-4xl">{signup?"Inicie sua construção.":"Bem-vindo de volta."}</h2><p className="mt-3 text-sm text-muted-foreground">Governe o corpo. Sustente a vida.</p><form onSubmit={submit} className="mt-10 space-y-4">{signup&&<Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo" maxLength={120} required/>}<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" maxLength={255} required/><Input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" minLength={8} maxLength={72} required/><Button variant="gold" className="h-12 w-full uppercase tracking-[0.14em]" disabled={busy}>{busy?"Processando...":signup?"Criar acesso":"Entrar"}</Button></form>{message&&<p className="mt-4 text-sm text-primary" role="status">{message}</p>}<div className="my-7 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>ou<span className="h-px flex-1 bg-border"/></div><Button variant="quiet" className="h-12 w-full" onClick={google}>Continuar com Google</Button><div className="mt-8 flex justify-between text-xs"><button className="text-muted-foreground hover:text-foreground" onClick={()=>setSignup(!signup)}>{signup?"Já tenho acesso":"Criar minha conta"}</button><Link to="/forgot-password" className="text-muted-foreground hover:text-foreground">Recuperar senha</Link></div></div></section></main>}