import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";
import { Brand } from "@/components/sim/Brand";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [{ title: "Privacidade — Radar da Performance" }, { name: "description", content: "Como o Shape Is Money utiliza e protege os dados do Radar da Performance." }, { property: "og:title", content: "Privacidade — Radar da Performance" }, { property: "og:description", content: "Informações sobre identificação, respostas, análise e contato no Radar da Performance." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: PrivacyPage,
});

function PrivacyPage() { return <main className="min-h-screen bg-background px-5 py-8 text-foreground sm:px-10"><div className="mx-auto max-w-3xl"><Brand compact/><Link to="/radar" className="mt-12 inline-flex items-center gap-2 text-xs uppercase text-primary"><ArrowLeft className="size-4"/>Voltar ao Radar</Link><p className="sim-kicker mt-16">Privacidade</p><h1 className="mt-4 text-5xl sm:text-7xl">Seus dados, sob controle.</h1><div className="mt-10 space-y-8 border-t border-border pt-8 text-sm leading-7 text-foreground/75"><section><h2 className="text-2xl text-foreground">O que coletamos</h2><p className="mt-3">Nome, contato, idade, contexto profissional, origem da visita e respostas fornecidas voluntariamente no Radar da Performance.</p></section><section><h2 className="text-2xl text-foreground">Para que utilizamos</h2><p className="mt-3">Para salvar seu progresso, calcular sua pontuação, gerar uma leitura individual e um relatório, apresentar seu resultado e permitir contato relacionado ao Shape Is Money.</p></section><section><h2 className="text-2xl text-foreground">Como protegemos</h2><p className="mt-3">Respostas e dados pessoais não ficam publicamente disponíveis. O resultado usa um endereço individual não enumerável, e o painel completo é restrito à equipe autorizada.</p></section><section><h2 className="text-2xl text-foreground">Inteligência artificial</h2><p className="mt-3">A pontuação é calculada por regras determinísticas. A inteligência artificial interpreta os dados fornecidos, sem substituir avaliação médica e sem criar promessas financeiras.</p></section><section><h2 className="text-2xl text-foreground">Seus direitos</h2><p className="mt-3">Você pode solicitar acesso, correção ou exclusão de seus dados pelo mesmo canal de contato utilizado pela equipe Shape Is Money.</p></section><p className="border-t border-border pt-8 text-xs text-muted-foreground">Versão 1.0 · Atualizada em 29 de setembro de 2026.</p></div></div></main>; }