import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from "lucide-react";
import { Brand } from "@/components/sim/Brand";
import { CinematicBackdrop } from "@/components/sim/CinematicBackdrop";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";
import { createRadarLead, finalizeRadar, getRadarPublicConfig, resumeRadar, saveRadarAnswer, trackRadarVisit } from "@/lib/radar.functions";
import type { RadarQuestion } from "@/lib/radar-score";

export const Route = createFileRoute("/radar/")({
  head: () => ({ meta: [{ title: "Radar da Performance — Shape Is Money" }, { name: "description", content: "Descubra como sua performance está distribuída entre os cinco pilares da metodologia Shape Is Money." }, { property: "og:title", content: "Radar da Performance — Shape Is Money" }, { property: "og:description", content: "Seu corpo está no mesmo nível da vida que você construiu?" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: RadarPage,
});

type Credentials = { sessionId: string; secret: string; resultToken: string };
type Identity = { fullName: string; whatsapp: string; email: string; age: string; jobTitle: string; company: string; segment: string; consent: boolean; website: string };
const emptyIdentity: Identity = { fullName: "", whatsapp: "", email: "", age: "", jobTitle: "", company: "", segment: "", consent: false, website: "" };
const storageKey = "sim-radar-session-v1";

function RadarPage() {
  const navigate = useNavigate();
  const getConfig = useServerFn(getRadarPublicConfig); const trackVisit = useServerFn(trackRadarVisit); const createLead = useServerFn(createRadarLead); const resume = useServerFn(resumeRadar); const saveAnswer = useServerFn(saveRadarAnswer); const finishRadar = useServerFn(finalizeRadar);
  const [phase, setPhase] = useState<"landing"|"identity"|"questions"|"analyzing">("landing"); const [config, setConfig] = useState<any>(null); const [questions, setQuestions] = useState<RadarQuestion[]>([]); const [identity, setIdentity] = useState<Identity>(emptyIdentity); const [credentials, setCredentials] = useState<Credentials|null>(null); const [answers, setAnswers] = useState<Record<string, number>>({}); const [index, setIndex] = useState(0); const [value, setValue] = useState(3); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const params = useMemo(() => typeof window === "undefined" ? new URLSearchParams() : new URLSearchParams(window.location.search), []);
  useEffect(() => { void (async () => { try { const response = await getConfig(); setConfig(response.settings); setQuestions(response.questions as RadarQuestion[]); const visitorId = localStorage.getItem("sim-radar-visitor") ?? crypto.randomUUID(); localStorage.setItem("sim-radar-visitor", visitorId); await trackVisit({ data: { visitorId, source: params.get("utm_source") ?? "direct", utmSource: params.get("utm_source") ?? undefined, utmMedium: params.get("utm_medium") ?? undefined, utmCampaign: params.get("utm_campaign") ?? undefined, landingPage: window.location.href } }); const saved = localStorage.getItem(storageKey); if (!saved) return; const parsed = JSON.parse(saved) as Credentials; const restored = await resume({ data: { sessionId: parsed.sessionId, secret: parsed.secret } }); if (restored.completed) { await navigate({ to: "/radar/result/$token", params: { token: parsed.resultToken } }); return; } setCredentials(parsed); setQuestions(restored.questions as RadarQuestion[]); setAnswers(Object.fromEntries(restored.answers.map((item: any) => [item.question_id, item.answer_value]))); setIndex(Math.min(restored.currentQuestion, Math.max(0, restored.questions.length - 1))); setPhase("questions"); } catch { localStorage.removeItem(storageKey); } })(); }, []);
  const current = questions[index]; useEffect(() => { if (current) setValue(answers[current.id] ?? 3); }, [current?.id]);
  const validIdentity = identity.fullName.trim().length >= 3 && identity.whatsapp.trim().length >= 8 && /\S+@\S+\.\S+/.test(identity.email) && Number(identity.age) >= 18 && identity.jobTitle.trim().length >= 2 && identity.company.trim().length >= 2 && identity.segment.trim().length >= 2 && identity.consent;
  async function identify() { if (!validIdentity) { setError("Preencha os campos e confirme o consentimento para continuar."); return; } setBusy(true); setError(""); try { const created = await createLead({ data: { ...identity, age: Number(identity.age), consent: true as const, source: params.get("utm_source") ?? "direct", utmSource: params.get("utm_source") ?? undefined, utmMedium: params.get("utm_medium") ?? undefined, utmCampaign: params.get("utm_campaign") ?? undefined, utmContent: params.get("utm_content") ?? undefined, utmTerm: params.get("utm_term") ?? undefined, referrer: document.referrer || undefined, landingPage: window.location.href } }); const next = created as Credentials; localStorage.setItem(storageKey, JSON.stringify(next)); setCredentials(next); setPhase("questions"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível iniciar o Radar."); } finally { setBusy(false); } }
  async function advance() { if (!current || !credentials) return; setBusy(true); setError(""); try { await saveAnswer({ data: { sessionId: credentials.sessionId, secret: credentials.secret, questionId: current.id, value, position: index + 1 } }); setAnswers(previous => ({ ...previous, [current.id]: value })); if (index < questions.length - 1) setIndex(index + 1); else { setPhase("analyzing"); await finishRadar({ data: { sessionId: credentials.sessionId, secret: credentials.secret } }); await navigate({ to: "/radar/result/$token", params: { token: credentials.resultToken } }); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar sua resposta."); if (phase === "analyzing") setPhase("questions"); } finally { setBusy(false); } }
  if (!config) return <main className="grid min-h-screen place-items-center bg-background"><p className="sim-kicker">Preparando o Radar</p></main>;
  if (!config.campaign_active && phase === "landing") return <main className="grid min-h-screen place-items-center bg-background px-5 text-center"><div><Brand impact/><h1 className="mt-8 text-5xl">Radar em calibração.</h1><p className="mt-4 text-muted-foreground">Uma nova leitura será disponibilizada em breve.</p></div></main>;
  if (phase === "landing") return <main className="overflow-hidden bg-background"><section className="relative flex min-h-[92vh] flex-col justify-between px-5 py-7 sm:px-10 lg:px-14"><CinematicBackdrop/><header className="relative z-10 flex items-start justify-between"><Brand compact/><p className="sim-kicker text-right">Executive performance<br/>assessment</p></header><div className="sim-reveal relative z-10 mx-auto flex max-w-4xl flex-col items-center text-center"><p className="sim-kicker">Radar da Performance</p><h1 className="mt-6 text-5xl leading-[.95] sm:text-7xl lg:text-8xl">Seu corpo está no mesmo nível<br/><span className="text-primary">da vida que você construiu?</span></h1><p className="mt-7 max-w-xl text-sm leading-7 text-foreground/70">Descubra como sua performance está distribuída entre os cinco pilares da metodologia Shape Is Money.</p><Button variant="gold" className="mt-9 h-12 px-8" onClick={() => setPhase("identity")}>Descobrir meu Radar <ArrowRight/></Button></div><div className="relative z-10 grid grid-cols-5 gap-2 text-center text-[8px] uppercase text-foreground/50 sm:text-[10px]">{["Construção","Capacidade","Governo","Percepção","Execução"].map(item => <span key={item} className="border-t border-primary/40 pt-3">{item}</span>)}</div></section>{config.video_url && <section className="mx-auto max-w-5xl px-5 py-24 sm:px-10"><p className="sim-kicker">A primeira leitura</p><div className="mt-8 aspect-video overflow-hidden border border-border bg-card"><video className="h-full w-full object-cover" src={config.video_url} controls preload="metadata"/></div><Button variant="gold" className="mt-8" onClick={() => setPhase("identity")}>Iniciar meu Radar <ArrowRight/></Button></section>}</main>;
  if (phase === "identity") return <main className="relative min-h-screen overflow-hidden bg-background px-5 py-7 sm:px-10"><div className="sim-grain pointer-events-none absolute inset-0"/><div className="relative mx-auto max-w-5xl"><div className="flex items-center justify-between"><Brand compact/><button className="text-xs uppercase text-muted-foreground" onClick={() => setPhase("landing")}>Voltar</button></div><div className="mt-16 grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="sim-kicker">Identificação</p><h1 className="mt-5 text-5xl leading-tight sm:text-6xl">A leitura começa pelo seu contexto.</h1><p className="mt-5 text-sm leading-7 text-muted-foreground">Seu registro entra no nosso acompanhamento assim que esta etapa for concluída.</p></div><section className="border-y border-border py-7"><div className="grid gap-4 sm:grid-cols-2"><Input placeholder="Nome completo" value={identity.fullName} onChange={e=>setIdentity({...identity,fullName:e.target.value})}/><Input placeholder="WhatsApp" inputMode="tel" value={identity.whatsapp} onChange={e=>setIdentity({...identity,whatsapp:e.target.value})}/><Input placeholder="E-mail" type="email" value={identity.email} onChange={e=>setIdentity({...identity,email:e.target.value})}/><Input placeholder="Idade" type="number" min={18} max={100} value={identity.age} onChange={e=>setIdentity({...identity,age:e.target.value})}/><Input placeholder="Cargo / função" value={identity.jobTitle} onChange={e=>setIdentity({...identity,jobTitle:e.target.value})}/><Input placeholder="Empresa" value={identity.company} onChange={e=>setIdentity({...identity,company:e.target.value})}/><Input className="sm:col-span-2" placeholder="Segmento" value={identity.segment} onChange={e=>setIdentity({...identity,segment:e.target.value})}/><Input className="hidden" tabIndex={-1} autoComplete="off" aria-hidden="true" value={identity.website} onChange={e=>setIdentity({...identity,website:e.target.value})}/></div><label className="mt-6 flex items-start gap-3 text-xs leading-5 text-muted-foreground"><Checkbox checked={identity.consent} onCheckedChange={checked=>setIdentity({...identity,consent:checked===true})}/><span>Autorizo o uso das minhas respostas para gerar o Radar e o contato relacionado ao Shape Is Money. Li a <Link to="/privacy" className="text-primary underline">política de privacidade</Link>.</span></label>{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}<Button variant="gold" className="mt-7 w-full sm:w-auto" disabled={busy} onClick={()=>void identify()}>{busy?"Criando seu Radar":"Continuar"}<ArrowRight/></Button></section></div></div></main>;
  if (phase === "analyzing") return <AnalysisSequence/>;
  if (!current) return null;
  return <main className="relative flex min-h-screen flex-col overflow-hidden bg-background px-5 py-7 sm:px-10 lg:px-14"><div className="sim-grain pointer-events-none absolute inset-0"/><header className="relative z-10 flex items-start justify-between"><Brand compact/><div className="text-right"><p className="sim-kicker">Radar / {String(index + 1).padStart(2,"0")}</p><p className="mt-2 font-display text-2xl text-primary">{index + 1} / {questions.length}</p></div></header><div className="relative z-10 mt-7 h-px bg-muted"><div className="h-px bg-primary transition-all duration-700" style={{width:`${(index+1)/questions.length*100}%`}}/></div><section className="relative z-10 mx-auto flex w-full max-w-4xl flex-1 flex-col justify-center py-10"><p className="sim-kicker">{current.pillar} / {String((index%3)+1).padStart(2,"0")}</p><h1 className="mt-6 max-w-3xl text-4xl leading-tight sm:text-6xl">{current.prompt}</h1><div className="mt-12 max-w-2xl"><div className="mb-6 grid grid-cols-[1fr_auto_1fr] items-end gap-4 text-[9px] uppercase text-muted-foreground"><span>1 · {current.low_label}</span><strong className="font-display text-6xl font-normal text-primary">{value}</strong><span className="text-right">5 · {current.high_label}</span></div><Slider value={[value]} onValueChange={items=>setValue(items[0]??3)} min={1} max={5} step={1}/></div>{error&&<p className="mt-5 text-sm text-destructive">{error}</p>}<div className="mt-12 flex items-center justify-between"><Button variant="ghost" disabled={busy||index===0} onClick={()=>setIndex(Math.max(0,index-1))}><ArrowLeft/>Voltar</Button><Button variant="gold" disabled={busy} onClick={()=>void advance()}>{busy?"Salvando":index===questions.length-1?"Concluir Radar":"Continuar"}<ArrowRight/></Button></div></section></main>;
}

function AnalysisSequence(){const [step,setStep]=useState(0);const labels=["Construção mapeada","Capacidade mapeada","Governo mapeado","Percepção mapeada","Execução mapeada","Cruzando seus padrões"];useEffect(()=>{const timer=window.setInterval(()=>setStep(value=>Math.min(value+1,labels.length-1)),650);return()=>window.clearInterval(timer)},[]);return <main className="grid min-h-screen place-items-center bg-background px-5"><div className="w-full max-w-xl text-center"><Brand impact/><p className="sim-kicker mt-10">Analisando seu Radar</p><div className="mt-9 space-y-3 text-left">{labels.map((label,index)=><div key={label} className={`flex items-center justify-between border-b border-border py-3 transition-opacity ${index<=step?"opacity-100":"opacity-25"}`}><span className="text-xs uppercase">{label}</span>{index<step&&<Check className="size-4 text-primary"/>}</div>)}</div><p className="mt-8 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4"/>Pontuação calculada por regras determinísticas</p></div></main>}
