import { useEffect, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { BarChart3, BriefcaseBusiness, CalendarCheck2, ClipboardList, Dumbbell, Factory, HeartHandshake, Home, LibraryBig, LogOut, Menu, Network, ScanLine, Settings, Shield, Sparkles, UserRound, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Brand } from "./Brand";
import { Button } from "@/components/ui/button";
import { AdminCommandCenter } from "./AdminCommandCenter";
import { PermissionService } from "@/lib/permissions";
const memberNav = [
  { group: "Construção", items: [["/dashboard", "Hoje", Home], ["/training", "Meu plano", Dumbbell], ["/habits", "Hábitos", CalendarCheck2], ["/check-ins", "Check-in", ClipboardList], ["/performance", "Evolução", BarChart3], ["/perception-lab", "Percepção", ScanLine]] },
  { group: "Ecossistema", items: [["/network", "SIM Network", Network], ["/sim-select", "SIM Select", Sparkles], ["/experiences", "Experiences", Sparkles]] },
  { group: "Jornada", items: [["/my-journey", "Minha Jornada", HeartHandshake], ["/monthly-review", "Revisão mensal", ClipboardList]] },
  { group: "Conta", items: [["/profile", "Perfil", UserRound]] },
] as const;
const mobileNav = [["/dashboard", "Hoje", Home], ["/training", "Plano", Dumbbell], ["/habits", "Hábitos", CalendarCheck2], ["/check-ins", "Check-in", ClipboardList], ["/profile", "Perfil", UserRound]] as const;
const adminNav = [
  ["/admin", "Hoje", Home], ["/admin/clients", "Clientes", BriefcaseBusiness], ["/admin/production", "Produção", Factory], ["/admin/library", "Biblioteca", LibraryBig], ["/admin/business", "Negócio", BarChart3], ["/admin/settings", "Configurações", Settings],
] as const;
export function AppShell({ children, admin = false }: { children: React.ReactNode; admin?: boolean }) { const navigate = useNavigate(); const [staff,setStaff]=useState(admin); const [menuOpen,setMenuOpen]=useState(false); useEffect(()=>{if(admin)return;void(async()=>{const{data:user}=await supabase.auth.getUser();if(!user.user)return;const{data}=await supabase.from("user_roles").select("role").eq("user_id",user.user.id);setStaff(PermissionService.isStaff((data??[]).map(item=>item.role)))})()},[admin]); async function signOut() { await supabase.auth.signOut(); await navigate({ to: "/auth", replace: true }); }
  const navLink = (to:string,label:string,Icon:typeof Home) => <Link key={to} to={to} onClick={()=>setMenuOpen(false)} className="group flex min-w-0 items-center gap-3 border-l border-transparent px-3 py-2.5 text-[11px] uppercase tracking-[0.12em] text-muted-foreground transition-all duration-500 hover:border-primary hover:text-foreground" activeProps={{className:"border-primary bg-muted/40 text-foreground"}}><Icon className="size-3.5 shrink-0"/><span className="truncate">{label}</span></Link>;
  const navContent = admin ? <><p className="mt-10 text-[9px] uppercase tracking-[0.28em] text-muted-foreground">Administração</p><nav className="mt-5 flex-1 space-y-1">{adminNav.map(([to,label,Icon])=>navLink(to,label,Icon))}</nav></> : <nav className="mt-9 flex-1">{memberNav.map(section=><div key={section.group} className="mb-5"><p className="mb-2 px-3 text-[8px] uppercase tracking-[0.24em] text-muted-foreground/70">{section.group}</p>{section.items.map(([to,label,Icon])=>navLink(to,label,Icon))}</div>)}</nav>;
  return <div className="min-h-screen overflow-x-clip bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-30 hidden w-56 border-r border-border bg-sidebar/95 px-5 py-7 backdrop-blur-xl lg:flex lg:flex-col xl:w-60 xl:px-6"><Brand compact/>{navContent}{!admin&&staff&&navLink("/admin","Admin",Shield)}{admin&&navLink("/dashboard","Experiência membro",Home)}<Button variant="ghost" className="justify-start px-3 text-muted-foreground" onClick={signOut}><LogOut/>Sair</Button></aside><header className="sticky top-0 z-40 grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center gap-2 border-b border-border bg-background/90 px-4 backdrop-blur-xl sm:px-5 lg:hidden"><div className="min-w-0 overflow-hidden"><Brand compact/></div><div className="flex shrink-0 items-center gap-1">{admin&&<AdminCommandCenter/>}<Button variant="ghost" size="icon" aria-label="Abrir menu" onClick={()=>setMenuOpen(true)}><Menu className="size-4 text-primary"/></Button></div></header>{admin&&<div className="hidden h-16 items-center justify-end border-b border-border px-6 lg:ml-56 lg:flex xl:ml-60"><AdminCommandCenter/></div>}{menuOpen&&<div className="fixed inset-0 z-50 overflow-hidden bg-background/98 p-5 backdrop-blur-xl lg:hidden"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><div className="min-w-0"><Brand compact/></div><Button variant="ghost" size="icon" aria-label="Fechar menu" onClick={()=>setMenuOpen(false)}><X/></Button></div><div className="flex h-[calc(100%-4rem)] flex-col overflow-y-auto overscroll-contain pb-[max(1rem,env(safe-area-inset-bottom))]">{navContent}{!admin&&staff&&navLink("/admin","Admin",Shield)}{admin&&navLink("/dashboard","Experiência membro",Home)}<Button variant="ghost" className="mt-4 justify-start px-3" onClick={signOut}><LogOut/>Sair</Button></div></div>}<main className="min-w-0 pb-[calc(4rem+env(safe-area-inset-bottom))] lg:ml-56 lg:pb-0 xl:ml-60">{children}</main>{!admin&&<nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-border bg-sidebar/95 px-1 pb-[env(safe-area-inset-bottom)] backdrop-blur-xl lg:hidden">{mobileNav.map(([to,label,Icon])=><Link key={to} to={to} className="flex h-16 min-w-0 flex-col items-center justify-center gap-1 px-0.5 text-[7px] uppercase text-muted-foreground min-[430px]:text-[8px]" activeProps={{className:"text-primary"}}><Icon className="size-4 shrink-0"/><span className="max-w-full truncate">{label}</span></Link>)}</nav>}</div>;
}