import { useEffect, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { BarChart3, BrainCircuit, BriefcaseBusiness, CheckSquare, ClipboardList, Dumbbell, FileChartColumn, Home, LogOut, Menu, ScanLine, Settings, Shield, Sparkles, UserRound, UsersRound, Utensils, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Brand } from "./Brand";
import { Button } from "@/components/ui/button";
import { AdminCommandCenter } from "./AdminCommandCenter";
const memberNav = [
  { group: "Overview", items: [["/dashboard", "Home", Home]] },
  { group: "Performance", items: [["/performance", "Performance", BarChart3], ["/training", "Treino", Dumbbell], ["/nutrition", "Nutrição", Utensils], ["/perception-lab", "Perception Lab", ScanLine], ["/money-brain", "Money Brain", BrainCircuit]] },
  { group: "Ecossistema", items: [["/members", "Members", UsersRound], ["/sim-select", "SIM Select", Sparkles]] },
  { group: "Conta", items: [["/profile", "Perfil", UserRound]] },
] as const;
const mobileNav = [["/dashboard", "Home", Home], ["/training", "Treino", Dumbbell], ["/performance", "Performance", BarChart3], ["/members", "Members", UsersRound], ["/profile", "Perfil", UserRound]] as const;
const adminNav = [
  ["/admin", "CEO Overview", BarChart3], ["/admin/students", "Client Portfolio", BriefcaseBusiness], ["/admin/operations", "Operations", CheckSquare], ["/admin/training", "Training Intelligence", Dumbbell], ["/admin/intelligence", "Intelligence", BrainCircuit], ["/admin/tasks", "Tasks", ClipboardList], ["/admin/reports", "Reports", FileChartColumn], ["/admin/perception", "Perception", ScanLine], ["/admin/members", "Members", UsersRound], ["/admin/sim-select", "SIM Select", Sparkles], ["/admin/experiences", "Experiences", CheckSquare], ["/admin/money-brain", "AI Configuration", BrainCircuit], ["/admin/settings", "Settings", Settings],
] as const;
const staffRoles = ["coach", "nutritionist", "support", "manager", "admin", "admin_master", "content", "analyst"];
export function AppShell({ children, admin = false }: { children: React.ReactNode; admin?: boolean }) { const navigate = useNavigate(); const [staff,setStaff]=useState(admin); const [menuOpen,setMenuOpen]=useState(false); useEffect(()=>{if(admin)return;void(async()=>{const{data:user}=await supabase.auth.getUser();if(!user.user)return;const{data}=await supabase.from("user_roles").select("role").eq("user_id",user.user.id);setStaff(Boolean(data?.some(item=>staffRoles.includes(item.role))))})()},[admin]); async function signOut() { await supabase.auth.signOut(); await navigate({ to: "/auth", replace: true }); }
  const navLink = (to:string,label:string,Icon:typeof Home) => <Link key={to} to={to} onClick={()=>setMenuOpen(false)} className="group flex items-center gap-3 border-l border-transparent px-3 py-2.5 text-[11px] uppercase tracking-[0.12em] text-muted-foreground transition-all duration-500 hover:border-primary hover:text-foreground" activeProps={{className:"border-primary bg-muted/40 text-foreground"}}><Icon className="size-3.5"/>{label}</Link>;
  const navContent = admin ? <><p className="mt-10 text-[9px] uppercase tracking-[0.28em] text-muted-foreground">Administração</p><nav className="mt-5 flex-1 space-y-1">{adminNav.map(([to,label,Icon])=>navLink(to,label,Icon))}</nav></> : <nav className="mt-9 flex-1">{memberNav.map(section=><div key={section.group} className="mb-5"><p className="mb-2 px-3 text-[8px] uppercase tracking-[0.24em] text-muted-foreground/70">{section.group}</p>{section.items.map(([to,label,Icon])=>navLink(to,label,Icon))}</div>)}</nav>;
  return <div className="min-h-screen bg-background text-foreground"><aside className="fixed inset-y-0 left-0 z-30 hidden w-60 border-r border-border bg-sidebar/95 px-6 py-7 backdrop-blur-xl lg:flex lg:flex-col"><Brand compact/>{navContent}{!admin&&staff&&navLink("/admin","Admin",Shield)}{admin&&navLink("/dashboard","Experiência membro",Home)}<Button variant="ghost" className="justify-start px-3 text-muted-foreground" onClick={signOut}><LogOut/>Sair</Button></aside><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-border bg-background/90 px-5 backdrop-blur-xl lg:hidden"><Brand compact/><div className="flex items-center gap-1">{admin&&<AdminCommandCenter/>}<Button variant="ghost" size="icon" aria-label="Abrir menu" onClick={()=>setMenuOpen(true)}><Menu className="size-4 text-primary"/></Button></div></header>{admin&&<div className="hidden h-16 items-center justify-end border-b border-border px-6 lg:ml-60 lg:flex"><AdminCommandCenter/></div>}{menuOpen&&<div className="fixed inset-0 z-50 bg-background/98 p-6 backdrop-blur-xl lg:hidden"><div className="flex items-center justify-between"><Brand compact/><Button variant="ghost" size="icon" aria-label="Fechar menu" onClick={()=>setMenuOpen(false)}><X/></Button></div><div className="flex h-[calc(100%-4rem)] flex-col overflow-y-auto">{navContent}{!admin&&staff&&navLink("/admin","Admin",Shield)}{admin&&navLink("/dashboard","Experiência membro",Home)}<Button variant="ghost" className="mt-4 justify-start px-3" onClick={signOut}><LogOut/>Sair</Button></div></div>}<main className="pb-20 lg:ml-60 lg:pb-0">{children}</main>{!admin&&<nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-border bg-sidebar/95 px-1 backdrop-blur-xl lg:hidden">{mobileNav.map(([to,label,Icon])=><Link key={to} to={to} className="flex h-16 flex-col items-center justify-center gap-1 text-[8px] uppercase tracking-[0.08em] text-muted-foreground" activeProps={{className:"text-primary"}}><Icon className="size-4"/>{label}</Link>)}</nav>}</div>;
}