import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronDown, Circle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { TeamConversation } from "@/components/sim/TeamConversation";
import type { TodayAction } from "@/lib/today-first";

type PulsePoint = { id: string; total: number };

export function TodayStack({ name, greeting, date, actions, execution, completedWorkouts, plannedWorkouts, streak, score, direction, pulse }: { name:string; greeting:string; date:string; actions:TodayAction[]; execution:number|null; completedWorkouts:number; plannedWorkouts:number; streak:number; score:number|null; direction:string; pulse:PulsePoint[] }) {
  const priority = actions.find(action => !action.completed) ?? null;
  const completed = actions.filter(action => action.completed).length;
  const points = pulse.map((item,index)=>`${pulse.length===1?50:index/(pulse.length-1)*100},${100-item.total}`).join(" ");
  return <div className="mx-auto max-w-3xl px-4 py-6 sm:px-6 sm:py-10">
    <header className="border-b border-border pb-6"><p className="sim-kicker">{date}</p><h1 className="mt-3 text-4xl leading-none sm:text-6xl">{greeting}, {name}.</h1><p className="mt-3 text-sm text-muted-foreground">Seu dia organizado para executar sem procurar.</p></header>
    <section className="mt-5 border-l-2 border-primary bg-card/35 p-5 sm:p-7"><p className="sim-kicker">Prioridade agora</p>{priority?<><h2 className="mt-4 text-4xl leading-none sm:text-6xl">{priority.title}</h2><p className="mt-3 text-sm text-muted-foreground">{priority.detail}</p><Button asChild variant="gold" className="mt-7 h-14 w-full justify-between px-5 text-xs sm:w-auto sm:min-w-64"><Link to={priority.to}>{priority.kind==="training"?"Iniciar treino":"Abrir próxima ação"}<ArrowRight/></Link></Button></>:<div className="py-8"><Check className="size-8 text-primary"/><h2 className="mt-4 text-4xl">Dia concluído.</h2><p className="mt-2 text-sm text-muted-foreground">Seus registros de hoje estão em dia.</p></div>}</section>
    <section className="mt-7"><div className="flex items-end justify-between gap-4"><div><p className="sim-kicker">Seu dia</p><h2 className="mt-2 text-3xl">{completed} de {actions.length} concluídos</h2></div><span className="font-display text-3xl text-primary">{actions.length?Math.round(completed/actions.length*100):0}%</span></div><div className="mt-4 divide-y divide-border border-y border-border">{actions.map(action=><Link key={`${action.kind}-${action.title}`} to={action.to} className={`grid grid-cols-[24px_minmax(0,1fr)_auto] items-center gap-3 py-4 ${action.completed?"opacity-45":""}`}>{action.completed?<Check className="size-4 text-primary"/>:<Circle className="size-4 text-muted-foreground"/>}<span className="min-w-0"><strong className="block truncate text-sm font-normal">{action.title}</strong><span className="mt-1 block truncate text-[11px] text-muted-foreground">{action.detail}</span></span><span className="font-mono text-[10px] text-muted-foreground">{String(Math.floor(action.scheduledMinutes/60)).padStart(2,"0")}:{String(action.scheduledMinutes%60).padStart(2,"0")}</span></Link>)}</div></section>
    <section className="mt-7 overflow-x-auto border-y border-border [scrollbar-width:none]"><div className="grid min-w-[560px] grid-cols-4 divide-x divide-border"><Metric label="Execução" value={execution===null?"—":`${execution}%`}/><Metric label="Treinos" value={`${completedWorkouts}/${plannedWorkouts||"—"}`}/><Metric label="Sequência" value={`${streak} dias`}/><Metric label="SIM Score" value={score===null?"—":String(score)}/></div></section>
    <section className="mt-7 border-y border-border py-6"><p className="sim-kicker">Direção</p><blockquote className="mt-3 max-w-xl font-display text-2xl leading-tight">“{direction}”</blockquote></section>
    <Collapsible className="mt-5 border-b border-border pb-5"><CollapsibleTrigger asChild><Button variant="ghost" className="h-auto w-full justify-between px-0 py-3"><span className="text-left"><span className="sim-kicker block">SIM Pulse</span><span className="mt-2 block font-display text-2xl">Tendência recente</span></span><ChevronDown className="size-4 text-primary"/></Button></CollapsibleTrigger><CollapsibleContent><div className="mt-3 h-36 border-y border-border bg-[linear-gradient(to_bottom,transparent_49%,var(--border)_50%,transparent_51%)]">{pulse.length>1?<svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full text-primary" aria-label="Tendência recente do SIM Score"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.2" vectorEffect="non-scaling-stroke"/></svg>:<div className="grid h-full place-items-center px-5 text-center text-sm text-muted-foreground">A tendência aparecerá com novas leituras.</div>}</div></CollapsibleContent></Collapsible>
    <div className="mt-10"><TeamConversation contextType="general"/></div>
  </div>;
}
function Metric({label,value}:{label:string;value:string}) { return <div className="p-4"><p className="sim-kicker">{label}</p><p className="mt-3 font-display text-3xl">{value}</p></div> }
