import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Check, ImagePlus, Save } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/sim/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { requireStaff } from "@/lib/admin-guard";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
export const Route=createFileRoute("/_authenticated/admin/training/photo-protocol")({beforeLoad:requireStaff,head:()=>({meta:[{title:"Photo Protocol Configuration — SIM"},{name:"description",content:"Configuração oficial dos 17 registros fotográficos."},{property:"og:title",content:"Photo Protocol Configuration — SIM"},{property:"og:description",content:"Orientações e referências oficiais do protocolo fotográfico."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
const split=(v:string)=>v.split(",").map(x=>x.trim()).filter(Boolean);function configured(s:Tables<"photo_protocol_slots">){return Boolean(s.public_name&&s.instruction_text&&s.reference_asset_url&&s.camera_orientation&&s.framing_rules&&s.purpose&&s.analysis_tags.length)}
function Page(){const[slots,setSlots]=useState<Tables<"photo_protocol_slots">[]>([]);async function load(){const{data}=await supabase.from("photo_protocol_slots").select("*").eq("protocol_code","SIM_INITIAL_17").order("slot_number");setSlots(data??[])}useEffect(()=>{void load()},[]);const count=useMemo(()=>slots.filter(s=>!s.active||configured(s)).length,[slots]);async function update(slot:Tables<"photo_protocol_slots">,values:Partial<Tables<"photo_protocol_slots">>){const{error}=await supabase.from("photo_protocol_slots").update(values).eq("id",slot.id);if(error)toast.error(error.message);else await load()}async function upload(slot:Tables<"photo_protocol_slots">,file:File){const path=`protocol-references/${slot.id}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error}=await supabase.storage.from("training-private").upload(path,file,{contentType:file.type});if(error){toast.error(error.message);return}await update(slot,{reference_asset_url:path})}return <AppShell admin><div className="mx-auto max-w-6xl px-5 py-10"><p className="sim-kicker">Training · Photo Protocol Configuration</p><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><h1 className="text-5xl">17 Photo Protocol</h1><span className={count===17?"text-xs uppercase text-primary":"text-xs uppercase text-destructive"}>{count===17?"Configured":"Not configured"} · {count}/17</span></div><p className="mt-4 text-muted-foreground">O cliente só recebe o protocolo quando todos os slots ativos possuem orientação e referência oficiais.</p><div className="mt-10 space-y-6">{slots.map(slot=><SlotEditor key={slot.id} slot={slot} onSave={v=>update(slot,v)} onUpload={f=>upload(slot,f)}/>)}</div></div></AppShell>}
function SlotEditor({slot,onSave,onUpload}:{slot:Tables<"photo_protocol_slots">;onSave:(v:Partial<Tables<"photo_protocol_slots">>)=>Promise<void>;onUpload:(f:File)=>Promise<void>}){const[draft,setDraft]=useState({public_name:slot.public_name??"",instruction_text:slot.instruction_text??"",camera_orientation:slot.camera_orientation??"",framing_rules:slot.framing_rules??"",purpose:slot.purpose??"",analysis_tags:slot.analysis_tags.join(", "),active:slot.active});return <article className="border-y border-border py-6"><div className="flex items-center justify-between"><p className="sim-kicker">Slot {String(slot.slot_number).padStart(2,"0")}</p>{configured(slot)&&<Check className="size-4 text-primary"/>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input placeholder="Nome oficial" value={draft.public_name} onChange={e=>setDraft({...draft,public_name:e.target.value})}/><Input placeholder="Posição da câmera" value={draft.camera_orientation} onChange={e=>setDraft({...draft,camera_orientation:e.target.value})}/><Textarea className="rounded-none" placeholder="Instrução" value={draft.instruction_text} onChange={e=>setDraft({...draft,instruction_text:e.target.value})}/><Textarea className="rounded-none" placeholder="Enquadramento" value={draft.framing_rules} onChange={e=>setDraft({...draft,framing_rules:e.target.value})}/><Input placeholder="Finalidade" value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value})}/><Input placeholder="Tags de análise, separadas por vírgula" value={draft.analysis_tags} onChange={e=>setDraft({...draft,analysis_tags:e.target.value})}/></div><div className="mt-4 flex flex-wrap gap-3"><label className="inline-flex cursor-pointer items-center gap-2 border border-border px-4 py-2 text-xs"><ImagePlus className="size-4"/>{slot.reference_asset_url?"Substituir referência":"Adicionar referência"}<input className="hidden" type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void onUpload(f)}}/></label><Button variant="quiet" onClick={()=>void onSave({...draft,analysis_tags:split(draft.analysis_tags)})}><Save/>Salvar</Button><Button variant={draft.active?"gold":"quiet"} onClick={()=>{setDraft({...draft,active:!draft.active});void onSave({active:!draft.active})}}>{draft.active?"Ativo":"Inativo"}</Button></div></article>}