import { useCallback, useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, Clock3, ListFilter, RefreshCw } from "lucide-react";
import { AppShell } from "@/components/sim/AppShell";
import { Button } from "@/components/ui/button";
import { requireStaff } from "@/lib/admin-guard";
import { supabase } from "@/integrations/supabase/client";
import { useServerFn } from "@tanstack/react-start";
import { refreshClientOperations, runTrainingGeneration } from "@/lib/sim-orchestrator.functions";

export const Route=createFileRoute("/_authenticated/admin/production")({beforeLoad:requireStaff,head:()=>({meta:[{title:"Delivery Center — Shape Is Money"},{name:"description",content:"Tudo que está sendo construído para os clientes."},{property:"og:title",content:"Delivery Center — Shape Is Money"},{property:"og:description",content:"Fila única da operação e das revisões humanas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});

type Activation={id:string;client_id:string;plan:string;status:string;current_stage:string;stage_started_at:string;target_delivery_at:string;next_action:string;next_action_owner:string;profiles:{first_name:string;last_name:string}|null};
type Job={id:string;client_id:string;status:string;error_message:string|null;attempts:number;updated_at:string;program_id:string|null};
type Nutrition={id:string;user_id:string;status:string;updated_at:string;title:string};
type Scan={id:string;user_id:string;status:string;updated_at:string};
type QueueItem={key:string;clientId:string;name:string;plan:string;product:string;stage:string;owner:string;since:string;slaAt:string;action:string;kind:string;failed:boolean;jobId?:string};
const tabs=["TODOS","NOVOS","AGUARDANDO CLIENTE","ASSESSMENT","TREINO","NUTRIÇÃO","PERCEPTION","REVISÃO","PRONTO PARA PUBLICAR","ATIVOS","BLOQUEADOS"] as const;
const clientStages=["ONBOARDING_REQUIRED","BASELINE_REQUIRED","PHOTO_PROTOCOL_REQUIRED"];
const elapsed=(value:string)=>Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/3600000));
const sla=(item:QueueItem)=>item.failed||new Date(item.slaAt).getTime()<Date.now()?"OVERDUE":new Date(item.slaAt).getTime()-Date.now()<86400000?"AT RISK":"ON TRACK";
const matchTab=(item:QueueItem,tab:string)=>tab==="TODOS"||(tab==="NOVOS"&&item.stage==="PAYMENT_CONFIRMED")||(tab==="AGUARDANDO CLIENTE"&&item.owner==="CLIENT")||(tab==="ASSESSMENT"&&item.stage.includes("ASSESSMENT"))||(tab==="TREINO"&&item.product==="TREINO")||(tab==="NUTRIÇÃO"&&item.product==="NUTRIÇÃO")||(tab==="PERCEPTION"&&item.product==="PERCEPTION")||(tab==="REVISÃO"&&item.stage.includes("REVIEW"))||(tab==="PRONTO PARA PUBLICAR"&&["APPROVED","READY_TO_PUBLISH"].includes(item.stage))||(tab==="ATIVOS"&&["ACTIVE_PROTOCOL","PUBLISHED"].includes(item.stage))||(tab==="BLOQUEADOS"&&(item.failed||item.stage==="BLOCKED"));

function Page(){const[activations,setActivations]=useState<Activation[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[nutrition,setNutrition]=useState<Nutrition[]>([]);const[scans,setScans]=useState<Scan[]>([]);const[tab,setTab]=useState<(typeof tabs)[number]>("TODOS");const[busy,setBusy]=useState<string|null>(null);const retry=useServerFn(runTrainingGeneration);const refresh=useServerFn(refreshClientOperations);
const load=useCallback(async()=>{const[a,j,n,s]=await Promise.all([supabase.from("client_activations").select("id,client_id,plan,status,current_stage,stage_started_at,target_delivery_at,next_action,next_action_owner,profiles!client_activations_client_id_fkey(first_name,last_name)").order("target_delivery_at"),supabase.from("training_generation_jobs").select("id,client_id,status,error_message,attempts,updated_at,program_id").order("updated_at",{ascending:false}),supabase.from("nutrition_plans").select("id,user_id,status,updated_at,title").in("status",["draft","review"]),supabase.from("perception_scans").select("id,user_id,status,updated_at").in("status",["processing","ai_completed","failed"])]);setActivations((a.data??[]) as Activation[]);setJobs(j.data??[]);setNutrition(n.data??[]);setScans(s.data??[])},[]);
useEffect(()=>{void load();const channel=supabase.channel("production-center").on("postgres_changes",{event:"*",schema:"public",table:"client_activations"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"training_generation_jobs"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"nutrition_plans"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"perception_scans"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
const items=useMemo(()=>{const names=new Map(activations.map(a=>[a.client_id,`${a.profiles?.first_name??"Cliente"} ${a.profiles?.last_name??""}`.trim()]));const plans=new Map(activations.map(a=>[a.client_id,a.plan]));const base:QueueItem[]=activations.map(a=>({key:`activation-${a.id}`,clientId:a.client_id,name:names.get(a.client_id)??"Cliente",plan:a.plan,product:clientStages.includes(a.current_stage)?"CALIBRAÇÃO":a.current_stage.includes("ASSESSMENT")?"ASSESSMENT":"ATIVAÇÃO",stage:a.current_stage,owner:a.next_action_owner,since:a.stage_started_at,slaAt:a.target_delivery_at,action:a.next_action,kind:"activation",failed:a.status==="BLOCKED"}));const training=jobs.map(j=>({key:`training-${j.id}`,clientId:j.client_id,name:names.get(j.client_id)??"Cliente",plan:plans.get(j.client_id)??"—",product:"TREINO",stage:j.status,owner:["DRAFT_READY","HUMAN_REVIEW","APPROVED","FAILED"].includes(j.status)?"BRUNO":"SYSTEM",since:j.updated_at,slaAt:activations.find(a=>a.client_id===j.client_id)?.target_delivery_at??j.updated_at,action:j.status==="FAILED"?"Ver erro e tentar novamente":j.status==="DRAFT_READY"?"Revisar treino":"Acompanhar geração",kind:"training",failed:j.status==="FAILED",jobId:j.id} satisfies QueueItem));const food=nutrition.map(n=>({key:`nutrition-${n.id}`,clientId:n.user_id,name:names.get(n.user_id)??"Cliente",plan:plans.get(n.user_id)??"—",product:"NUTRIÇÃO",stage:n.status.toUpperCase(),owner:n.status==="review"?"BRUNO":"TEAM",since:n.updated_at,slaAt:activations.find(a=>a.client_id===n.user_id)?.target_delivery_at??n.updated_at,action:n.status==="review"?"Revisar orientação":"Continuar construção",kind:"nutrition",failed:false} satisfies QueueItem));const perception=scans.map(s=>({key:`scan-${s.id}`,clientId:s.user_id,name:names.get(s.user_id)??"Cliente",plan:plans.get(s.user_id)??"—",product:"PERCEPTION",stage:s.status.toUpperCase(),owner:s.status==="ai_completed"?"BRUNO":"SYSTEM",since:s.updated_at,slaAt:activations.find(a=>a.client_id===s.user_id)?.target_delivery_at??s.updated_at,action:s.status==="ai_completed"?"Revisar leitura":s.status==="failed"?"Ver erro":"Processando",kind:"perception",failed:s.status==="failed"} satisfies QueueItem));return [...base,...training,...food,...perception]},[activations,jobs,nutrition,scans]);const filtered=items.filter(item=>matchTab(item,tab));
async function retryItem(item:QueueItem){setBusy(item.key);if(item.kind==="training")await retry({data:{clientId:item.clientId,force:true}});else await refresh({data:{clientId:item.clientId,event:"reassessment.due"}});await load();setBusy(null)}
return <AppShell admin><div className="mx-auto max-w-[1500px] px-5 py-10"><header><p className="sim-kicker">Produção</p><h1 className="mt-4 text-5xl">Delivery Center</h1><p className="mt-3 text-muted-foreground">Tudo que está sendo construído para os clientes.</p></header><div className="mt-8 flex gap-2 overflow-x-auto border-y border-border py-3">{tabs.map(item=><Button key={item} variant={tab===item?"gold":"ghost"} className="shrink-0" onClick={()=>setTab(item)}>{item} <span className="ml-1 opacity-60">{items.filter(row=>matchTab(row,item)).length}</span></Button>)}</div><div className="mt-7 overflow-x-auto border-y border-border"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="border-b border-border text-[9px] uppercase text-muted-foreground"><tr>{["Cliente","Plano","Produto","Etapa","Responsável","Tempo","SLA","Próxima ação"].map(x=><th key={x} className="px-4 py-4 font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.key} className="border-b border-border/60"><td className="px-4 py-5"><Link className="story-link" to="/admin/students/$studentId" params={{studentId:item.clientId}}>{item.name}</Link></td><td className="px-4 py-5 uppercase text-primary">{item.plan}</td><td className="px-4 py-5">{item.product}</td><td className="px-4 py-5 text-xs">{item.stage.replaceAll("_"," ")}</td><td className="px-4 py-5"><span className="sim-kicker">{item.owner}</span></td><td className="px-4 py-5 text-xs"><Clock3 className="mr-1 inline size-3"/>{elapsed(item.since)}h</td><td className={`px-4 py-5 text-xs ${sla(item)==="OVERDUE"?"text-destructive":"text-primary"}`}>{sla(item)}</td><td className="px-4 py-5"><div className="flex items-center justify-between gap-3"><span className="text-xs">{item.action}</span>{item.failed?<Button size="sm" variant="quiet" disabled={busy===item.key} onClick={()=>void retryItem(item)}><RefreshCw/>Tentar novamente</Button>:<Button asChild size="icon" variant="ghost" aria-label="Abrir cliente"><Link to="/admin/students/$studentId" params={{studentId:item.clientId}}><ArrowRight/></Link></Button>}</div>{item.failed&&<span className="mt-2 flex items-center gap-1 text-[10px] text-destructive"><AlertTriangle className="size-3"/>Falha registrada; nenhum draft foi publicado.</span>}</td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="px-5 py-16 text-center text-muted-foreground"><ListFilter className="mx-auto mb-3 size-5"/>Nenhum trabalho nesta condição.</td></tr>}</tbody></table></div></div></AppShell>}
