import { useCallback, useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Activity, AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, CircleGauge, Clock3, LoaderCircle, MessageSquareText, ShieldAlert, UserRound, UsersRound } from "lucide-react";
import { AppShell } from "@/components/sim/AppShell";
import { requireStaff } from "@/lib/admin-guard";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/admin/")({beforeLoad:requireStaff,head:()=>({meta:[{title:"Hoje — SIM Command Center"},{name:"description",content:"O que precisa de decisão humana agora."},{property:"og:title",content:"Hoje — SIM Command Center"},{property:"og:description",content:"Decisões, processamento e pendências dos clientes."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});

type Profile={id:string;first_name:string;last_name:string;plan:string};
type Activation={client_id:string;current_stage:string;status:string;next_action:string;next_action_owner:string;stage_started_at:string};
type Job={client_id:string;status:string;error_message:string|null;updated_at:string};
type Scan={user_id:string;status:string;updated_at:string};
type Assessment={client_id:string;status:string;updated_at:string;approved_at:string|null};
type Analysis={client_id:string;status:string;error_message:string|null;updated_at:string};
type Comment={client_id:string;status:string;message:string;created_at:string};
type Alert={client_id:string;reason:string;priority:string;created_at:string};
type Session={user_id:string;completion_percent:number|null;completed_at:string|null};
type Checkin={user_id:string;checkin_date:string};
type Item={clientId:string;name:string;title:string;detail:string;kind:"human"|"system"|"client";updatedAt:string};

function Page(){
  const[profiles,setProfiles]=useState<Profile[]>([]);const[activations,setActivations]=useState<Activation[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[plans,setPlans]=useState<Job[]>([]);const[scans,setScans]=useState<Scan[]>([]);const[assessments,setAssessments]=useState<Assessment[]>([]);const[analyses,setAnalyses]=useState<Analysis[]>([]);const[comments,setComments]=useState<Comment[]>([]);const[alerts,setAlerts]=useState<Alert[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[checkins,setCheckins]=useState<Checkin[]>([]);const[protocolCount,setProtocolCount]=useState(0);
  const load=useCallback(async()=>{const since=new Date(Date.now()-30*86400000).toISOString();const[p,a,j,n,s,as,an,cm,al,ws,ci,pr]=await Promise.all([
    supabase.from("profiles").select("id,first_name,last_name,plan"),supabase.from("client_activations").select("client_id,current_stage,status,next_action,next_action_owner,stage_started_at"),supabase.from("training_generation_jobs").select("client_id,status,error_message,updated_at").in("status",["READY","GENERATING","NEEDS_LIBRARY","DRAFT_READY","HUMAN_REVIEW","APPROVED","FAILED"]),supabase.from("nutrition_generation_jobs").select("client_id,status,error_message,updated_at").neq("status","PUBLISHED"),supabase.from("perception_scans").select("user_id,status,updated_at").in("status",["processing","ai_completed","failed"]),supabase.from("assessments").select("client_id,status,updated_at,approved_at").in("status",["ready_for_review","processing"]),supabase.from("anamnesis_analyses").select("client_id,status,error_message,updated_at").in("status",["processing","failed"]),supabase.from("contextual_comments").select("client_id,status,message,created_at").eq("status","open"),supabase.from("relationship_alerts").select("client_id,reason,priority,created_at").eq("status","open"),supabase.from("workout_sessions").select("user_id,completion_percent,completed_at").gte("started_at",since),supabase.from("daily_checkins").select("user_id,checkin_date").gte("created_at",since),supabase.from("protocols").select("id",{count:"exact",head:true}).eq("status","published")
  ]);setProfiles((p.data??[]) as Profile[]);setActivations((a.data??[]) as Activation[]);setJobs(j.data??[]);setPlans(n.data??[]);setScans(s.data??[]);setAssessments(as.data??[]);setAnalyses(an.data??[]);setComments(cm.data??[]);setAlerts(al.data??[]);setSessions(ws.data??[]);setCheckins(ci.data??[]);setProtocolCount(pr.count??0)},[]);
  useEffect(()=>{void load();const channel=supabase.channel(`admin-cockpit-${crypto.randomUUID()}`).on("postgres_changes",{event:"*",schema:"public",table:"client_activations"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"training_generation_jobs"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"nutrition_generation_jobs"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"contextual_comments"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"relationship_alerts"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
  const groups=useMemo(()=>{const names=new Map(profiles.map(p=>[p.id,`${p.first_name||"Cliente"} ${p.last_name||""}`.trim()]));const name=(id:string)=>names.get(id)??"Cliente";const items:Item[]=[];for(const a of activations)items.push({clientId:a.client_id,name:name(a.client_id),title:a.next_action,detail:a.current_stage.replaceAll("_"," "),kind:a.next_action_owner==="CLIENT"?"client":a.next_action_owner==="SYSTEM"?"system":"human",updatedAt:a.stage_started_at});for(const j of jobs){if(["GENERATING","READY"].includes(j.status))items.push({clientId:j.client_id,name:name(j.client_id),title:"Training Intelligence",detail:j.status==="GENERATING"?"Gerando estratégia":"Na fila de geração",kind:"system",updatedAt:j.updated_at});else items.push({clientId:j.client_id,name:name(j.client_id),title:j.status==="NEEDS_LIBRARY"?"Biblioteca requer decisão":j.status==="FAILED"?"Falha no draft de treino":"Treino para revisar",detail:j.error_message??j.status,kind:"human",updatedAt:j.updated_at})}for(const n of plans)items.push({clientId:n.client_id,name:name(n.client_id),title:"Nutrition Intelligence",detail:n.error_message??n.status,kind:["DRAFT_READY","HUMAN_REVIEW","FAILED"].includes(n.status)?"human":"system",updatedAt:n.updated_at});for(const s of scans)items.push({clientId:s.user_id,name:name(s.user_id),title:"Perception",detail:s.status==="processing"?"Processando fotos":s.status,kind:s.status==="processing"?"system":"human",updatedAt:s.updated_at});for(const a of assessments)items.push({clientId:a.client_id,name:name(a.client_id),title:"Assessment",detail:a.status,kind:a.status==="processing"?"system":"human",updatedAt:a.updated_at});for(const a of analyses)items.push({clientId:a.client_id,name:name(a.client_id),title:"Anamnese",detail:a.error_message??a.status,kind:a.status==="processing"?"system":"human",updatedAt:a.updated_at});for(const c of comments)items.push({clientId:c.client_id,name:name(c.client_id),title:"Novo comentário",detail:c.message,kind:"human",updatedAt:c.created_at});return{human:items.filter(x=>x.kind==="human"),system:items.filter(x=>x.kind==="system"),client:items.filter(x=>x.kind==="client"),names}},[profiles,activations,jobs,plans,scans,assessments,analyses,comments]);
  const completed=sessions.filter(item=>item.completed_at);const execution=completed.length?Math.round(completed.reduce((sum,item)=>sum+(item.completion_percent??0),0)/completed.length):null;const activeClients=new Set(activations.filter(item=>item.status!=="CANCELLED").map(item=>item.client_id)).size;const clientsWithCheckin=new Set(checkins.map(item=>item.user_id)).size;const attention=[...alerts.map(item=>({clientId:item.client_id,name:groups.names.get(item.client_id)??"Cliente",reason:item.reason,updatedAt:item.created_at})),...comments.map(item=>({clientId:item.client_id,name:groups.names.get(item.client_id)??"Cliente",reason:"Novo comentário",updatedAt:item.created_at}))].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const greeting=new Date().getHours()<12?"Bom dia":new Date().getHours()<18?"Boa tarde":"Boa noite";const pulse=[{label:"Execução média",value:execution===null?"—":`${execution}%`,detail:`${completed.length} treinos concluídos`},{label:"Check-ins em 30 dias",value:String(checkins.length),detail:`${clientsWithCheckin} clientes registraram`},{label:"Protocolos ativos",value:String(protocolCount),detail:"publicados"},{label:"Clientes com atenção",value:String(new Set(attention.map(item=>item.clientId)).size),detail:"por sinais reais"},{label:"Comentários recentes",value:String(comments.length),detail:"abertos"}];
  return <AppShell admin><main className="relative min-h-[calc(100vh-4rem)] overflow-hidden px-4 py-5 sm:px-6 lg:px-8"><div className="sim-grain pointer-events-none absolute inset-0 opacity-15"/><div className="relative mx-auto max-w-[1500px]">
    <header className="grid min-w-0 gap-3 border-b border-border pb-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-end sm:gap-5"><div className="min-w-0"><p className="sim-kicker">Shape Is Money Command Center</p><h1 className="mt-2 text-3xl leading-none sm:text-5xl">{greeting}, Bruno.</h1><p className="mt-2 text-xs text-muted-foreground">O que precisa de você agora.</p></div><p className="hidden shrink-0 items-center gap-2 text-[10px] uppercase text-muted-foreground sm:flex"><CalendarDays className="size-3 shrink-0 text-primary"/>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"long"}).format(new Date())}</p></header>
    <section className="mt-4"><p className="sim-kicker">Resumo operacional</p><div className="mt-2 grid grid-cols-2 border border-border bg-card/20 sm:grid-cols-5"><AdminKpi label="Clientes ativos" value={activeClients} icon={UsersRound}/><AdminKpi label="Precisam de você" value={groups.human.length} icon={UserRound}/><AdminKpi label="OS trabalhando" value={groups.system.length} icon={LoaderCircle}/><AdminKpi label="Aguardando cliente" value={groups.client.length} icon={Clock3}/><AdminKpi label="Alertas" value={alerts.length} icon={ShieldAlert} className="col-span-2 sm:col-span-1"/></div></section>
    <section className="mt-3 grid gap-3 xl:grid-cols-[minmax(0,1.8fr)_minmax(300px,.72fr)]"><div className="grid gap-3"><Queue title="Precisa de você" eyebrow="Julgamento humano" items={groups.human} empty="Nenhuma decisão humana pendente." icon={UserRound}/><Queue title="OS trabalhando" eyebrow="Processos ativos" items={groups.system} empty="Nenhum processamento em andamento." icon={LoaderCircle}/><Queue title="Aguardando cliente" eyebrow="Próxima ação do cliente" items={groups.client} empty="Nenhum cliente parado nesta etapa." icon={Clock3}/></div><aside className="grid content-start gap-3"><section className="border border-border bg-card/25 p-5"><div className="flex items-center justify-between"><div><p className="sim-kicker">Pulso da operação</p><h2 className="mt-2 text-2xl">Últimos 30 dias</h2></div><CircleGauge className="size-5 text-primary"/></div><div className="mt-4 divide-y divide-border">{pulse.map(item=><div key={item.label} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 py-3"><span className="min-w-0"><span className="block text-[10px] uppercase text-muted-foreground">{item.label}</span><span className="mt-1 block truncate text-[10px] text-muted-foreground/70">{item.detail}</span></span><strong className="font-display text-3xl font-normal text-primary">{item.value}</strong></div>)}</div></section><section className="border border-border bg-card/25 p-5"><div className="flex items-center justify-between"><p className="sim-kicker">Atenção</p><AlertTriangle className="size-4 text-primary"/></div><div className="mt-3 divide-y divide-border">{attention.slice(0,6).map((item,index)=><Link key={`${item.clientId}-${index}`} to="/admin/students/$studentId" params={{studentId:item.clientId}} className="group grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 py-3"><span className="min-w-0"><strong className="block truncate text-sm font-normal">{item.name}</strong><span className="mt-1 block truncate text-[10px] text-muted-foreground">{item.reason}</span></span><ArrowRight className="size-3 text-primary transition-transform group-hover:translate-x-1"/></Link>)}{!attention.length&&<p className="py-4 text-xs text-muted-foreground">Nenhum sinal de atenção aberto.</p>}</div></section><div className="grid grid-cols-3 border border-border bg-card/20"><QuickLink to="/admin/production" label="Produção" icon={Activity}/><QuickLink to="/admin/clients" label="Clientes" icon={UserRound}/><QuickLink to="/admin/relationship" label="Relação" icon={MessageSquareText}/></div></aside></section>
  </div></main></AppShell>;
}

function AdminKpi({label,value,icon:Icon,className=""}:{label:string;value:number;icon:typeof UsersRound;className?:string}){return <article className={`border-b border-r border-border p-3 last:border-r-0 sm:border-b-0 ${className}`}><div className="flex items-center justify-between"><p className="text-[8px] uppercase tracking-[.16em] text-muted-foreground">{label}</p><Icon className="size-3 text-primary"/></div><p className="mt-2 font-display text-4xl leading-none">{value}</p></article>}
function Queue({title,eyebrow,items,empty,icon:Icon}:{title:string;eyebrow:string;items:Item[];empty:string;icon:typeof UserRound}){return <section className="min-w-0 border border-border bg-card/20"><header className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 border-b border-border px-4 py-3"><div className="min-w-0"><p className="sim-kicker truncate">{eyebrow}</p><h2 className="mt-1 truncate text-2xl">{title}</h2></div><span className="flex shrink-0 items-center gap-2 font-display text-3xl text-primary"><Icon className="size-4"/>{items.length}</span></header><div className="divide-y divide-border">{items.slice(0,5).map((item,index)=><Link key={`${item.kind}-${item.clientId}-${index}`} to="/admin/students/$studentId" params={{studentId:item.clientId}} className="group grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-center gap-x-3 gap-y-1 px-4 py-3 sm:grid-cols-[minmax(0,1.25fr)_minmax(100px,.75fr)_auto]"><span className="min-w-0"><strong className="block truncate text-sm font-normal">{item.title}</strong><span className="mt-1 block truncate text-[10px] text-muted-foreground">{item.name}</span></span><span className="col-start-1 min-w-0 truncate text-[9px] uppercase text-muted-foreground sm:col-start-auto">{item.detail}</span><ArrowRight className="col-start-2 row-span-2 row-start-1 size-3 shrink-0 text-primary transition-transform group-hover:translate-x-1 sm:col-start-auto sm:row-span-1"/></Link>)}{!items.length&&<div className="flex items-start gap-2 px-4 py-4 text-xs text-muted-foreground"><CheckCircle2 className="mt-0.5 size-3 shrink-0 text-primary"/><span>{empty}</span></div>}</div>{items.length>5&&<Link to="/admin/production" className="flex items-center justify-between gap-3 border-t border-border px-4 py-2 text-[9px] uppercase text-primary">Ver fila completa <ArrowRight className="size-3 shrink-0"/></Link>}</section>}
function QuickLink({to,label,icon:Icon}:{to:"/admin/production"|"/admin/clients"|"/admin/relationship";label:string;icon:typeof Activity}){return <Link to={to} className="grid place-items-center gap-2 border-r border-border p-3 text-[9px] uppercase text-muted-foreground last:border-r-0 hover:text-foreground"><Icon className="size-4 text-primary"/>{label}</Link>}