import { useCallback, useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Clock3 } from "lucide-react";
import { AppShell } from "@/components/sim/AppShell";
import { requireStaff } from "@/lib/admin-guard";
import { supabase } from "@/integrations/supabase/client";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";

export const Route=createFileRoute("/_authenticated/admin/operations")({beforeLoad:requireStaff,head:()=>({meta:[{title:"Delivery Queue — SIM Command Center"},{name:"description",content:"Ativações, responsáveis e prazos de entrega."},{property:"og:title",content:"Delivery Queue — SIM Command Center"},{property:"og:description",content:"Operação de entrega orientada por etapas reais."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
type Row={id:string;client_id:string;plan:string;status:string;current_stage:string;stage_started_at:string;target_delivery_at:string;next_action:string;next_action_owner:string;profiles:{first_name:string;last_name:string}|null};
const columns=["NEW CLIENT","COLLECTING DATA","TRAINING GENERATION","TRAINING REVIEW","NUTRITION BUILD","READY TO PUBLISH","ACTIVE"] as const;
const columnFor=(row:Row)=>row.current_stage==="PAYMENT_CONFIRMED"?"NEW CLIENT":["ONBOARDING_REQUIRED","BASELINE_REQUIRED","PHOTO_PROTOCOL_REQUIRED","ASSESSMENT_PROCESSING","ASSESSMENT_REVIEW","CYCLE_STRATEGY"].includes(row.current_stage)?"COLLECTING DATA":row.current_stage==="TRAINING_GENERATION"?"TRAINING GENERATION":row.current_stage==="TRAINING_REVIEW"?"TRAINING REVIEW":row.current_stage==="NUTRITION_BUILD"?"NUTRITION BUILD":["FINAL_REVIEW","READY_TO_PUBLISH"].includes(row.current_stage)?"READY TO PUBLISH":"ACTIVE";
const elapsed=(value:string)=>Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/3600000));
const sla=(row:Row)=>row.status==="COMPLETED"?"COMPLETE":new Date(row.target_delivery_at).getTime()<Date.now()?"OVERDUE":new Date(row.target_delivery_at).getTime()-Date.now()<86400000?"AT RISK":"ON TRACK";
function Page(){const[rows,setRows]=useState<Row[]>([]);const[plan,setPlan]=useState("all");const[status,setStatus]=useState("all");const load=useCallback(async()=>{const{data}=await supabase.from("client_activations").select("id,client_id,plan,status,current_stage,stage_started_at,target_delivery_at,next_action,next_action_owner,profiles!client_activations_client_id_fkey(first_name,last_name)").order("target_delivery_at");setRows((data??[]) as Row[])},[]);useEffect(()=>{void load();const channel=supabase.channel("delivery-queue").on("postgres_changes",{event:"*",schema:"public",table:"client_activations"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);const filtered=useMemo(()=>rows.filter(row=>(plan==="all"||row.plan===plan)&&(status==="all"||sla(row)===status)),[rows,plan,status]);return <AppShell admin><div className="mx-auto max-w-[1500px] overflow-x-auto px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="sim-kicker">Operations</p><h1 className="mt-4 text-5xl">Delivery Queue</h1><p className="mt-3 text-muted-foreground">Uma etapa, um responsável e uma próxima ação por cliente.</p></div><div className="flex gap-3"><Select value={plan} onValueChange={setPlan}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os planos</SelectItem>{["paid","plus","premium"].map(x=><SelectItem key={x} value={x}>{x.toUpperCase()}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os SLAs</SelectItem>{["ON TRACK","AT RISK","OVERDUE","COMPLETE"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div><div className="mt-9 grid min-w-[1160px] grid-cols-7 gap-px bg-border">{columns.map(column=><section key={column} className="min-h-96 bg-background p-3"><p className="text-[9px] uppercase text-muted-foreground">{column}</p><p className="mt-2 font-display text-3xl">{filtered.filter(row=>columnFor(row)===column).length}</p><div className="mt-5 space-y-3">{filtered.filter(row=>columnFor(row)===column).map(row=><Link key={row.id} to="/admin/students/$studentId" params={{studentId:row.client_id}} className="block border border-border p-3 transition-colors hover:border-primary"><span className="block text-sm">{row.profiles?.first_name} {row.profiles?.last_name}</span><span className="mt-2 block text-[9px] uppercase text-muted-foreground">{row.plan} · {row.next_action_owner}</span><span className={`mt-3 flex items-center gap-1 text-[9px] ${sla(row)==="OVERDUE"?"text-destructive":"text-primary"}`}><Clock3 className="size-3"/>{elapsed(row.stage_started_at)}h na etapa · {sla(row)}</span><span className="mt-3 flex items-center justify-between text-xs">{row.next_action}<ArrowRight className="size-3"/></span></Link>)}</div></section>)}</div></div></AppShell>}
