import { useCallback, useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, LoaderCircle, UserRound } from "lucide-react";
import { AppShell } from "@/components/sim/AppShell";
import { requireStaff } from "@/lib/admin-guard";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/admin/")({beforeLoad:requireStaff,head:()=>({meta:[{title:"Hoje — SIM Command Center"},{name:"description",content:"O que precisa de decisão humana agora."},{property:"og:title",content:"Hoje — SIM Command Center"},{property:"og:description",content:"Decisões, processamento e pendências dos clientes."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
type Activation={client_id:string;current_stage:string;status:string;next_action:string;next_action_owner:string;stage_started_at:string;profiles:{first_name:string;last_name:string}|null};
type Job={client_id:string;status:string;error_message:string|null;updated_at:string};
type Plan={client_id:string;status:string;error_message:string|null;updated_at:string};
type Scan={user_id:string;status:string;updated_at:string};
type Assessment={client_id:string;status:string;updated_at:string;approved_at:string|null};
type Analysis={client_id:string;status:string;error_message:string|null;updated_at:string};
type Comment={client_id:string;status:string;message:string;created_at:string};
type Item={clientId:string;name:string;title:string;detail:string;kind:"human"|"system"|"client"};
function Page(){const[activations,setActivations]=useState<Activation[]>([]);const[jobs,setJobs]=useState<Job[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[scans,setScans]=useState<Scan[]>([]);const[assessments,setAssessments]=useState<Assessment[]>([]);const[analyses,setAnalyses]=useState<Analysis[]>([]);const[comments,setComments]=useState<Comment[]>([]);const load=useCallback(async()=>{const[a,j,n,s,as,an,cm]=await Promise.all([supabase.from("client_activations").select("client_id,current_stage,status,next_action,next_action_owner,stage_started_at,profiles!client_activations_client_id_fkey(first_name,last_name)"),supabase.from("training_generation_jobs").select("client_id,status,error_message,updated_at").in("status",["READY","GENERATING","NEEDS_LIBRARY","DRAFT_READY","HUMAN_REVIEW","APPROVED","FAILED"]),supabase.from("nutrition_generation_jobs").select("client_id,status,error_message,updated_at").neq("status","PUBLISHED"),supabase.from("perception_scans").select("user_id,status,updated_at").in("status",["processing","ai_completed","failed"]),supabase.from("assessments").select("client_id,status,updated_at,approved_at").in("status",["ready_for_review","processing"]),supabase.from("anamnesis_analyses").select("client_id,status,error_message,updated_at").in("status",["processing","failed"]),supabase.from("contextual_comments").select("client_id,status,message,created_at").eq("status","open")]);setActivations((a.data??[]) as Activation[]);setJobs(j.data??[]);setPlans(n.data??[]);setScans(s.data??[]);setAssessments(as.data??[]);setAnalyses(an.data??[]);setComments(cm.data??[])},[]);useEffect(()=>{void load();const channel=supabase.channel("admin-today").on("postgres_changes",{event:"*",schema:"public",table:"client_activations"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"training_generation_jobs"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"nutrition_generation_jobs"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"assessments"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"anamnesis_analyses"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"contextual_comments"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
const groups=useMemo(()=>{const names=new Map(activations.map(a=>[a.client_id,`${a.profiles?.first_name??"Cliente"} ${a.profiles?.last_name??""}`.trim()]));const items:Item[]=[];for(const a of activations){const kind:Item["kind"]=a.next_action_owner==="CLIENT"?"client":a.next_action_owner==="SYSTEM"?"system":"human";items.push({clientId:a.client_id,name:names.get(a.client_id)??"Cliente",title:a.next_action,detail:a.current_stage.replaceAll("_"," "),kind})}for(const j of jobs){if(j.status==="GENERATING"||j.status==="READY")items.push({clientId:j.client_id,name:names.get(j.client_id)??"Cliente",title:"Training Intelligence em processamento",detail:j.status,kind:"system"});if(["NEEDS_LIBRARY","DRAFT_READY","HUMAN_REVIEW","APPROVED","FAILED"].includes(j.status))items.push({clientId:j.client_id,name:names.get(j.client_id)??"Cliente",title:j.status==="NEEDS_LIBRARY"?"Completar a Biblioteca para gerar treino":j.status==="FAILED"?"Falha no draft de treino":"Treino pronto para revisão",detail:j.error_message??j.status,kind:"human"})}for(const n of plans){const human=["DRAFT_READY","HUMAN_REVIEW","FAILED"].includes(n.status);items.push({clientId:n.client_id,name:names.get(n.client_id)??"Cliente",title:n.status==="HUMAN_REVIEW"?"Nutrição pronta para revisão":n.status==="FAILED"?"Falha na produção nutricional":"Nutrição em preparação",detail:n.error_message??n.status,kind:human?"human":"system"})}for(const s of scans)items.push({clientId:s.user_id,name:names.get(s.user_id)??"Cliente",title:s.status==="ai_completed"?"Perception pronto para revisão":"Perception em processamento",detail:s.status,kind:s.status==="ai_completed"||s.status==="failed"?"human":"system"});for(const a of assessments)items.push({clientId:a.client_id,name:names.get(a.client_id)??"Cliente",title:a.status==="ready_for_review"?"Assessment pronto para revisão":"Assessment em processamento",detail:a.status,kind:a.status==="ready_for_review"?"human":"system"});for(const a of analyses)items.push({clientId:a.client_id,name:names.get(a.client_id)??"Cliente",title:a.status==="failed"?"Falha na leitura da anamnese":"Anamnese em análise",detail:a.error_message??a.status,kind:a.status==="failed"?"human":"system"});for(const c of comments)items.push({clientId:c.client_id,name:names.get(c.client_id)??"Cliente",title:"Nova mensagem do cliente",detail:c.message,kind:"human"});return{human:items.filter(x=>x.kind==="human"),system:items.filter(x=>x.kind==="system"),client:items.filter(x=>x.kind==="client")}},[activations,jobs,plans,scans,assessments,analyses,comments]);const greeting=new Date().getHours()<12?"Bom dia":new Date().getHours()<18?"Boa tarde":"Boa noite";
const Section=({title,subtitle,items,kind}:{title:string;subtitle:string;items:Item[];kind:Item["kind"]})=><section className="border-t border-border py-9"><div className="flex items-end justify-between gap-4"><div><p className="sim-kicker">{subtitle}</p><h2 className="mt-3 text-4xl">{title}</h2></div><span className="font-display text-5xl text-primary">{items.length}</span></div><div className="mt-7 divide-y divide-border border-y border-border">{items.slice(0,8).map((item,index)=><Link key={`${kind}-${item.clientId}-${index}`} to="/admin/students/$studentId" params={{studentId:item.clientId}} className="grid gap-3 py-5 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><span><span className="block text-lg">{item.title}</span><span className="mt-1 block text-xs text-muted-foreground">{item.name}</span></span><span className="text-xs text-muted-foreground">{item.detail}</span><ArrowRight className="size-4 text-primary"/></Link>)}{!items.length&&<div className="flex items-center gap-3 py-8 text-sm text-muted-foreground"><CheckCircle2 className="size-4 text-primary"/>Nenhuma ação nesta condição.</div>}</div>{items.length>8&&<Link to="/admin/production" className="mt-4 inline-flex items-center gap-2 text-xs text-primary">Ver todos <ArrowRight className="size-3"/></Link>}</section>;
return <AppShell admin><div className="mx-auto max-w-7xl px-5 py-10"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-border pb-10"><div><p className="sim-kicker">Shape Is Money Command Center</p><h1 className="mt-4 text-5xl">{greeting}, Bruno.</h1><p className="mt-4 text-muted-foreground">O que precisa de você agora.</p></div><p className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-4"/>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"full"}).format(new Date())}</p></header><Section title="Precisa de você" subtitle="Julgamento humano" items={groups.human} kind="human"/><Section title="OS trabalhando" subtitle="Em processamento" items={groups.system} kind="system"/><Section title="Aguardando cliente" subtitle="Próxima ação do cliente" items={groups.client} kind="client"/><div className="grid gap-px border-y border-border bg-border sm:grid-cols-3"><Link to="/admin/production" className="bg-background p-6"><LoaderCircle className="size-5 text-primary"/><span className="mt-4 block text-lg">Abrir Produção</span></Link><Link to="/admin/clients" className="bg-background p-6"><UserRound className="size-5 text-primary"/><span className="mt-4 block text-lg">Encontrar cliente</span></Link><Link to="/admin/production" search={{}} className="bg-background p-6"><Clock3 className="size-5 text-primary"/><span className="mt-4 block text-lg">Ver SLAs</span></Link></div></div></AppShell>}
