import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/sim/AppShell";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";

export const Route = createFileRoute("/_authenticated/check-ins")({ head: () => ({ meta: [{ title: "Check-in — SIM OS" }, { name: "description", content: "Registre os sinais essenciais do seu dia." }, { property: "og:title", content: "Check-in — SIM OS" }, { property: "og:description", content: "Menos de vinte segundos para registrar sua execução." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });
const signals = [{ key: "sleep", label: "Sono", low: "Muito ruim", high: "Excelente", min: 1 }, { key: "energy", label: "Energia", low: "Muito baixa", high: "Excelente", min: 1 }, { key: "stress", label: "Estresse", low: "Muito baixo", high: "Muito alto", min: 1 }, { key: "pain", label: "Dor ou desconforto", low: "Nenhum", high: "Intenso", min: 0 }, { key: "hydration", label: "Hidratação", low: "Muito baixa", high: "Excelente", min: 1 }] as const;
type Values = Record<(typeof signals)[number]["key"], number>;
function Page() { const [values, setValues] = useState<Values>({ sleep: 3, energy: 3, stress: 3, pain: 0, hydration: 3 }); const [trained, setTrained] = useState<boolean | null>(null); const [nutrition, setNutrition] = useState<boolean | null>(null); const [done, setDone] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { void (async () => { const { data: userData } = await supabase.auth.getUser(); if (!userData.user) return; const today = new Date().toLocaleDateString("en-CA"); const { data } = await supabase.from("daily_checkins").select("*").eq("user_id", userData.user.id).eq("checkin_date", today).maybeSingle(); if (data) { setValues({ sleep: data.sleep_quality ?? 3, energy: data.energy ?? 3, stress: data.stress ?? 3, pain: data.pain ?? 0, hydration: data.hydration ?? 3 }); setTrained(data.trained); setNutrition(data.nutrition_on_track); } })(); }, []);
  async function save() { setSaving(true); const { data: userData } = await supabase.auth.getUser(); if (!userData.user) return; const checkinDate = new Date().toLocaleDateString("en-CA"); const { error } = await supabase.from("daily_checkins").upsert({ user_id: userData.user.id, checkin_date: checkinDate, sleep_quality: values.sleep, energy: values.energy, stress: values.stress, pain: values.pain, hydration: values.hydration, trained, nutrition_on_track: nutrition }, { onConflict: "user_id,checkin_date" }); if (!error) { await supabase.from("crm_events").insert({ user_id: userData.user.id, event_type: "checkin.completed", metadata: { checkin_date: checkinDate } }); setDone(true); } setSaving(false); }
  return <AppShell><div className="mx-auto max-w-3xl px-5 py-10"><div className="flex items-end justify-between"><div><p className="sim-kicker">Check-in diário · menos de 20 segundos</p><h1 className="mt-4 text-5xl">Registre os sinais.</h1></div><Button asChild variant="ghost"><Link to="/weekly-review">Revisão semanal</Link></Button></div>{done ? <div className="sim-panel mt-10 p-12 text-center"><Check className="mx-auto size-10 text-primary"/><h2 className="mt-5 text-3xl">Evidência registrada.</h2><p className="mt-2 text-muted-foreground">Sua carteira já considera o check-in de hoje.</p><Button asChild variant="quiet" className="mt-7"><Link to="/dashboard">Ver carteira</Link></Button></div> : <div className="mt-10 space-y-8">{signals.map((signal) => <div key={signal.key} className="border-b border-border pb-7"><div className="flex items-end justify-between"><span>{signal.label}</span><strong className="font-display text-4xl text-primary">{values[signal.key]}</strong></div><Slider className="mt-5" value={[values[signal.key]]} min={signal.min} max={5} step={1} onValueChange={(next) => setValues({ ...values, [signal.key]: next[0] ?? values[signal.key] })}/><div className="mt-3 flex justify-between text-[9px] uppercase tracking-[0.12em] text-muted-foreground"><span>{signal.min} · {signal.low}</span><span>5 · {signal.high}</span></div></div>)}{[["Treinou?", trained, setTrained], ["Alimentação sob controle?", nutrition, setNutrition]].map(([label, value, setter]) => <div key={String(label)} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><span>{String(label)}</span><div className="flex gap-2"><Button variant={value === true ? "gold" : "quiet"} onClick={() => typeof setter === "function" && setter(true)}>Sim</Button><Button variant={value === false ? "gold" : "quiet"} onClick={() => typeof setter === "function" && setter(false)}>Não</Button></div></div>)}<Button variant="gold" className="h-12 w-full" disabled={saving || trained === null || nutrition === null} onClick={save}>{saving ? "Salvando" : "Confirmar check-in"}</Button></div>}</div></AppShell>;
}