import { useCallback, useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Circle, LoaderCircle } from "lucide-react";
import { AppShell } from "@/components/sim/AppShell";
import { UsageTracker } from "@/components/sim/UsageTracker";
import { MoneyBrainBrief } from "@/components/sim/MoneyBrainBrief";
import { ScoreRing } from "@/components/sim/ScoreRing";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { buildDailyBrief } from "@/lib/money-brain";
import { activationStages, deriveOperationalStatus, experienceMode, stageProgress, type OperationalActivation, type TrainingJobStatus } from "@/lib/client-operational-status";

export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Member Home — Shape Is Money"},{name:"description",content:"Seu ambiente privado de performance executiva."},{property:"og:title",content:"Member Home — Shape Is Money"},{property:"og:description",content:"Governe o corpo. Sustente a vida."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
type Data={profile:Tables<"profiles">;roles:string[];score:Tables<"sim_scores">|null;checkins:Tables<"daily_checkins">[];sessions:Tables<"workout_sessions">[];protocol:Tables<"protocols">|null;program:Tables<"workout_programs">|null;nutrition:Tables<"nutrition_plans">|null;scan:Tables<"perception_scans">|null;activation:OperationalActivation|null;job:{status:TrainingJobStatus}|null;photoCount:number;assessmentApproved:boolean};

function Page(){
  const[data,setData]=useState<Data|null>(null);
  const load=useCallback(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const id=auth.user.id;const[p,s,c,w,pr,t,n,scan,roles,activation,job,photos,assessment]=await Promise.all([supabase.from("profiles").select("*").eq("id",id).single(),supabase.from("sim_scores").select("*").eq("user_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("daily_checkins").select("*").eq("user_id",id).order("checkin_date").limit(14),supabase.from("workout_sessions").select("*").eq("user_id",id).order("started_at",{ascending:false}).limit(20),supabase.from("protocols").select("*").eq("user_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("workout_programs").select("*").eq("user_id",id).eq("status","published").order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("nutrition_plans").select("*").eq("user_id",id).eq("status","published").order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("perception_scans").select("*").eq("user_id",id).in("status",["ai_completed","reviewed"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("user_roles").select("role").eq("user_id",id),supabase.from("client_activations").select("current_stage,status,next_action,next_action_owner,target_delivery_at,stage_started_at").eq("client_id",id).maybeSingle(),supabase.from("training_generation_jobs").select("status").eq("client_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("assessment_photos").select("id",{count:"exact",head:true}).eq("client_id",id),supabase.from("assessments").select("approved_at,status").eq("client_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(p.data)setData({profile:p.data,roles:(roles.data??[]).map(x=>x.role),score:s.data,checkins:c.data??[],sessions:w.data??[],protocol:pr.data,program:t.data,nutrition:n.data,scan:scan.data,activation:activation.data as OperationalActivation|null,job:job.data as Data["job"],photoCount:photos.count??0,assessmentApproved:Boolean(assessment.data?.approved_at||assessment.data?.status==="approved")})},[]);
  useEffect(()=>{void load();let channel:ReturnType<typeof supabase.channel>|null=null;void supabase.auth.getUser().then(({data})=>{if(!data.user)return;channel=supabase.channel(`member-operations-${data.user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"client_activations",filter:`client_id=eq.${data.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"training_generation_jobs",filter:`client_id=eq.${data.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"workout_programs",filter:`user_id=eq.${data.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"nutrition_plans",filter:`user_id=eq.${data.user.id}`},()=>void load()).subscribe()});return()=>{if(channel)void supabase.removeChannel(channel)}},[load]);
  const brief=useMemo(()=>data?buildDailyBrief({checkins:data.checkins,sessions:data.sessions,latestScan:data.scan,hasNutrition:Boolean(data.nutrition)}):null,[data]);
  if(!data||!brief)return <AppShell><UsageTracker module="dashboard"/><div className="grid min-h-[70vh] place-items-center"><p className="sim-kicker">Preparando o ambiente</p></div></AppShell>;
  const checked=data.checkins.some(x=>x.checkin_date===new Date().toLocaleDateString("en-CA"));const beta=data.roles.includes("beta_member")||data.roles.includes("admin_master");const operational=deriveOperationalStatus({activation:data.activation,trainingStatus:data.job?.status??null,nutritionStatus:data.nutrition?.status??null,perceptionStatus:data.scan?.status??null});const mode=experienceMode(data.profile.plan,data.activation);const currentProgress=stageProgress(data.activation?.current_stage??null);const headlines={FREE_DISCOVERY:"Descubra seu ponto de partida.",PAID_ACTIVATION:"Seu protocolo está sendo construído.",PAID_ACTIVE:"Seu protocolo está ativo.",PLUS_ACTIVE:"Performance integrada, em execução.",PREMIUM_CONCIERGE:"Sua operação de performance, em curso."};const working=data.job?.status==="GENERATING";const review=["DRAFT_READY","HUMAN_REVIEW","APPROVED"].includes(data.job?.status??"");
  const milestones=[["Calibração",Boolean(data.profile.onboarding_completed_at)],["SIM Baseline",Boolean(data.score)],["Protocolo fotográfico",data.photoCount>=17],["Assessment review",data.assessmentApproved],["Protocolo executivo",data.protocol?.status==="published"],["Treino publicado",Boolean(data.program)],["Nutrição publicada",Boolean(data.nutrition)],["Perception Scan",Boolean(data.scan)],["Primeiro check-in",data.checkins.length>0],["Primeiro treino",data.sessions.some(x=>x.status==="completed")]] as const;
  const accesses=[["Performance","Seus sinais e evolução","/performance",true],["Training",data.program?.title??(review?"Em revisão humana":working?"Estratégia em processamento":"Protocolo em construção"),"/training",true],["Nutrition",data.nutrition?.title??"Orientação em preparação","/nutrition",true],["Perception Lab",data.scan?`Coerência ${data.scan.coherence_score??"—"}`:"Sua leitura visual privada","/perception-lab",beta||data.profile.plan!=="free"],["SIM Select","Menos escolha. Mais critério.","/sim-select",beta||data.profile.plan!=="free"],["SIM Network","Rede privada de membros","/network",true],["Experiences","Acesso por interesse","/experiences",beta||["plus","premium"].includes(data.profile.plan)]] as const;
  return <AppShell><UsageTracker module="dashboard"/><div className="mx-auto max-w-7xl px-5 py-10"><header className="grid gap-8 border-b border-border pb-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="sim-kicker">Shape Is Money Member · {data.profile.first_name}</p><h1 className="mt-4 text-6xl sm:text-7xl">{headlines[mode]}</h1><p className="mt-5 max-w-2xl text-muted-foreground">{mode==="PAID_ACTIVATION"?"Cada etapa utiliza seus dados reais e passa por revisão humana antes da liberação.":"Governe o corpo. Sustente a vida."}</p></div><Button asChild variant={checked?"quiet":"gold"}><Link to="/check-ins">{checked?"Check-in registrado":"Realizar check-in"}</Link></Button></header>
  {data.activation&&<section className="border-b border-border py-10"><p className="sim-kicker">Activation Timeline</p><div className="mt-7 grid grid-cols-3 gap-px bg-border sm:grid-cols-9">{activationStages.map((item,index)=>{const done=index<currentProgress||data.activation?.status==="COMPLETED";const current=index===currentProgress&&data.activation?.status!=="COMPLETED";return <div key={item.key} className="min-h-24 bg-background p-3"><span className={`font-display text-xl ${done||current?"text-primary":"text-muted-foreground"}`}>{done?<CheckCircle2 className="size-4"/>:item.short}</span><p className="mt-4 text-[9px] uppercase text-muted-foreground">{item.label}</p></div>})}</div></section>}
  <section className="border-b border-border py-10"><p className="sim-kicker">O que preciso fazer agora?</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h2 className="text-4xl">{operational.nextAction}</h2><p className="mt-2 text-sm text-muted-foreground">{working?"Organizando evidências, prioridades e estrutura semanal. Nenhuma publicação será automática.":review?"O draft permanece privado até a revisão e publicação da equipe.":`Responsável: ${operational.responsible}`}</p></div>{operational.nextRoute&&<Button asChild variant="gold"><Link to={operational.nextRoute}>Continuar <ArrowRight/></Link></Button>}{working&&<LoaderCircle className="size-6 animate-spin text-primary"/>}</div></section>
  <section className="grid gap-10 border-b border-border py-10 lg:grid-cols-[260px_1fr]"><div>{data.score?<ScoreRing score={data.score.total}/>:<p className="text-muted-foreground">Baseline ainda não realizado.</p>}</div><div className="grid gap-px bg-border sm:grid-cols-3"><div className="bg-background p-6"><p className="sim-kicker">Protocolo</p><p className="mt-4 text-2xl">{data.protocol?.status==="published"?"Publicado":"Em construção"}</p></div><div className="bg-background p-6"><p className="sim-kicker">Treino</p><p className="mt-4 text-2xl">{data.program?.title??(review?"Em revisão":"Em preparação")}</p></div><div className="bg-background p-6"><p className="sim-kicker">SLA interno</p><p className="mt-4 text-2xl">{operational.sla}</p></div></div></section>
  <div className="py-10"><MoneyBrainBrief brief={brief}/></div><section className="border-t border-border py-12"><p className="sim-kicker">Member access</p><h2 className="mt-3 text-4xl">Seu ecossistema</h2><div className="mt-8 divide-y divide-border border-y border-border">{accesses.map(([title,detail,to,enabled],index)=>enabled?<Link key={title} to={to} className="grid gap-3 py-7 sm:grid-cols-[70px_1fr_1fr_auto] sm:items-center"><span className="font-display text-3xl text-muted-foreground">0{index+1}</span><span className="text-2xl">{title}</span><span className="text-sm text-muted-foreground">{detail}</span><ArrowRight className="size-4 text-primary"/></Link>:<div key={title} className="grid gap-3 py-7 opacity-45 sm:grid-cols-[70px_1fr_1fr_auto] sm:items-center"><span className="font-display text-3xl text-muted-foreground">0{index+1}</span><span className="text-2xl">{title}</span><span className="text-sm text-muted-foreground">Disponível em outro plano</span><Circle className="size-3"/></div>)}</div></section><section className="border-t border-border py-10"><p className="sim-kicker">System progress</p><div className="mt-6 flex flex-wrap gap-5">{milestones.map(([label,done])=><span key={label} className="flex items-center gap-2 text-xs text-muted-foreground">{done?<CheckCircle2 className="size-4 text-primary"/>:<Circle className="size-4"/>}{label}</span>)}</div></section></div></AppShell>;
}