import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/sim/AppShell";
import { CinematicEntry } from "@/components/sim/CinematicEntry";
import { TodayStack } from "@/components/sim/TodayStack";
import { UsageTracker } from "@/components/sim/UsageTracker";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { buildDailyBrief } from "@/lib/money-brain";
import type { OperationalActivation, TrainingJobStatus } from "@/lib/client-operational-status";
import { dayGreeting, prioritizeToday, type TodayAction } from "@/lib/today-first";

export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Command Center — Shape Is Money"},{name:"description",content:"Seu sistema privado de performance executiva."},{property:"og:title",content:"Command Center — Shape Is Money"},{property:"og:description",content:"O próximo movimento da sua performance."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});

type WorkoutPreview={id:string;name:string;estimated_minutes:number|null;sequence:number};
type Program=Tables<"workout_programs">&{workouts:WorkoutPreview[]};
type Habit=Pick<Tables<"client_habits">,"id"|"title"|"description"|"target_frequency"|"current_streak"|"pillar"|"period">&{habit_logs:Array<Pick<Tables<"habit_logs">,"log_date"|"completed">>};
type Data={profile:Tables<"profiles">;roles:string[];scores:Tables<"sim_scores">[];checkins:Tables<"daily_checkins">[];sessions:Tables<"workout_sessions">[];protocol:Tables<"protocols">|null;program:Program|null;nutrition:Tables<"nutrition_plans">|null;scan:Tables<"perception_scans">|null;activation:OperationalActivation|null;job:{status:TrainingJobStatus}|null;photoCount:number;assessmentApproved:boolean;habits:Habit[]};

function Page(){
  const[data,setData]=useState<Data|null>(null);const mounted=useRef(false);
  const load=useCallback(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const id=auth.user.id;const[p,s,c,w,pr,t,n,scan,roles,activation,job,photos,assessment,habits]=await Promise.all([
    supabase.from("profiles").select("*").eq("id",id).single(),supabase.from("sim_scores").select("*").eq("user_id",id).order("created_at",{ascending:false}).limit(12),supabase.from("daily_checkins").select("*").eq("user_id",id).order("checkin_date").limit(14),supabase.from("workout_sessions").select("*").eq("user_id",id).order("started_at",{ascending:false}).limit(20),supabase.from("protocols").select("*").eq("user_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("workout_programs").select("*,workouts(id,name,estimated_minutes,sequence)").eq("user_id",id).eq("status","published").order("published_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("nutrition_plans").select("*").eq("user_id",id).eq("status","published").order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("perception_scans").select("*").eq("user_id",id).in("status",["ai_completed","reviewed"]).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("user_roles").select("role").eq("user_id",id),supabase.from("client_activations").select("current_stage,status,next_action,next_action_owner,target_delivery_at,stage_started_at").eq("client_id",id).maybeSingle(),supabase.from("training_generation_jobs").select("status").eq("client_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("assessment_photos").select("id",{count:"exact",head:true}).eq("client_id",id),supabase.from("assessments").select("approved_at,status").eq("client_id",id).order("created_at",{ascending:false}).limit(1).maybeSingle(),supabase.from("client_habits").select("id,title,description,target_frequency,current_streak,pillar,period,habit_logs(log_date,completed)").eq("client_id",id).eq("status","active").order("created_at").limit(1)
  ]);if(p.data&&mounted.current)setData({profile:p.data,roles:(roles.data??[]).map(x=>x.role),scores:s.data??[],checkins:c.data??[],sessions:w.data??[],protocol:pr.data,program:t.data as unknown as Program|null,nutrition:n.data,scan:scan.data,activation:activation.data as OperationalActivation|null,job:job.data as Data["job"],photoCount:photos.count??0,assessmentApproved:Boolean(assessment.data?.approved_at||assessment.data?.status==="approved"),habits:(habits.data??[]) as Habit[]})},[]);
  useEffect(()=>{mounted.current=true;void load();let channel:ReturnType<typeof supabase.channel>|null=null;let cancelled=false;void supabase.auth.getUser().then(({data:auth})=>{if(!auth.user||cancelled)return;channel=supabase.channel(`member-today-${auth.user.id}-${crypto.randomUUID()}`).on("postgres_changes",{event:"*",schema:"public",table:"client_activations",filter:`client_id=eq.${auth.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"workout_programs",filter:`user_id=eq.${auth.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"daily_checkins",filter:`user_id=eq.${auth.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"workout_sessions",filter:`user_id=eq.${auth.user.id}`},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"habit_logs",filter:`client_id=eq.${auth.user.id}`},()=>void load()).subscribe()});return()=>{mounted.current=false;cancelled=true;if(channel)void supabase.removeChannel(channel)}},[load]);
  const score=data?.scores[0]??null;const brief=useMemo(()=>data?buildDailyBrief({checkins:data.checkins,sessions:data.sessions,latestScan:data.scan,hasNutrition:Boolean(data.nutrition)}):null,[data]);
  if(!data||!brief)return <AppShell><UsageTracker module="dashboard"/><div className="grid min-h-[70vh] place-items-center"><p className="sim-kicker">Preparando o ambiente</p></div></AppShell>;
  const now=new Date();const today=now.toLocaleDateString("en-CA");const checked=data.checkins.some(item=>item.checkin_date===today);const workouts=[...(data.program?.workouts??[])].sort((a,b)=>a.sequence-b.sequence);const sessionsToday=data.sessions.filter(item=>new Date(item.started_at).toLocaleDateString("en-CA")===today);const nextWorkout=workouts.find(workout=>!sessionsToday.some(session=>session.workout_id===workout.id&&session.completed_at))??workouts[0]??null;const activeHabit=data.habits[0]??null;const habitDone=activeHabit?.habit_logs.some(item=>item.log_date===today&&item.completed)??false;const completedWeek=data.sessions.filter(item=>item.completed_at&&Date.now()-new Date(item.completed_at).getTime()<=7*86400000);const execution=workouts.length?Math.min(100,Math.round(completedWeek.length/workouts.length*100)):null;
  const actions:TodayAction[]=[];
  if(nextWorkout)actions.push({kind:"training",title:nextWorkout.name,detail:`Treino prescrito${nextWorkout.estimated_minutes?` · ${nextWorkout.estimated_minutes} min`:""}`,completed:sessionsToday.some(item=>item.workout_id===nextWorkout.id&&Boolean(item.completed_at)),scheduledMinutes:1080,to:"/training"});
  if(activeHabit)actions.push({kind:"habit",title:activeHabit.title,detail:activeHabit.description||"Hábito prioritário",completed:habitDone,scheduledMinutes:480,to:"/habits"});
  if(data.nutrition)actions.push({kind:"nutrition",title:"Executar alimentação",detail:data.nutrition.title,completed:false,scheduledMinutes:750,to:"/nutrition"});
  actions.push({kind:"checkin",title:"Check SIM",detail:checked?"Registro de hoje concluído":"Registre seus sinais do dia",completed:checked,scheduledMinutes:1260,to:"/check-ins"});
  const ordered=prioritizeToday(actions,now);const signals=[{label:"Profile",status:data.profile.onboarding_completed_at?"READY":"PENDING",active:Boolean(data.profile.onboarding_completed_at)},{label:"Protocol",status:data.protocol?.status==="published"?"ACTIVE":"BUILDING",active:data.protocol?.status==="published"},{label:"Training",status:data.program?"SYNCED":"PENDING",active:Boolean(data.program)},{label:"Recovery",status:data.checkins.length?"MONITORING":"NO SIGNAL",active:data.checkins.length>0},{label:"Perception",status:data.scan?"MONITORING":"NO SIGNAL",active:Boolean(data.scan)}];
  return <AppShell><UsageTracker module="dashboard"/><CinematicEntry name={data.profile.first_name.toUpperCase()} priority={score?.priority||brief.priority} signals={signals} protocolTitle={data.program?.title}/><TodayStack name={data.profile.first_name} greeting={dayGreeting(now)} date={new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(now)} actions={ordered} execution={execution} completedWorkouts={completedWeek.length} plannedWorkouts={workouts.length} streak={activeHabit?.current_streak??0} score={score?.total??null} direction={score?.recommendation||brief.message} pulse={[...data.scores].reverse().map(item=>({id:item.id,total:item.total}))}/></AppShell>;
}
