import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { ScoreRing } from "@/components/sim/ScoreRing";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_authenticated/diagnosis")({ head: () => ({ meta: [{ title: "Diagnóstico Inicial — SIM OS" }, { name: "description", content: "Seu ponto de partida nos cinco pilares." }, { property: "og:title", content: "Diagnóstico Inicial — SIM OS" }, { property: "og:description", content: "Seu ponto de partida para construir coerência." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });

function Page() {
  const [score, setScore] = useState<Tables<"sim_scores"> | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { const { data: userData } = await supabase.auth.getUser(); if (!userData.user) return; const { data } = await supabase.from("sim_scores").select("*").eq("user_id", userData.user.id).order("created_at", { ascending: false }).limit(1).maybeSingle(); setScore(data); setLoading(false); })(); }, []);
  if (loading) return <main className="grid min-h-screen place-items-center"><p className="sim-kicker">Carregando seu baseline</p></main>;
  if (!score) return <main className="grid min-h-screen place-items-center px-5 text-center"><div><p className="sim-kicker">Diagnóstico inicial</p><h1 className="mt-5 text-5xl">Seu histórico começa aqui.</h1><p className="mt-4 text-muted-foreground">Complete sua primeira calibração para estabelecer seu baseline.</p><Button asChild variant="gold" className="mt-8"><Link to="/onboarding">Iniciar calibração <ArrowRight/></Link></Button></div></main>;
  const pillars = [["Construção", score.construction], ["Capacidade", score.capacity], ["Governo", score.governance], ["Percepção", score.perception], ["Execução", score.execution]];
  return <main className="min-h-screen px-5 py-10 lg:px-14"><p className="sim-kicker">Diagnóstico inicial SIM</p><div className="mt-5 grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><h1 className="text-5xl leading-tight sm:text-7xl">Seu baseline foi estabelecido.</h1><p className="mt-6 max-w-xl text-muted-foreground">Este índice representa os dados informados na sua calibração inicial e evoluirá conforme novos registros forem adicionados.</p><div className="mt-9 grid grid-cols-5 gap-px border-y border-border">{pillars.map(([label, value]) => <div key={String(label)} className="py-5 text-center"><p className="font-display text-2xl text-primary">{value}</p><p className="mt-2 text-[8px] uppercase tracking-[0.1em] text-muted-foreground">{label}</p></div>)}</div><Button asChild variant="gold" className="mt-9"><Link to="/dashboard">Abrir carteira <ArrowRight/></Link></Button></div><div className="sim-panel p-7"><ScoreRing score={score.total}/><div className="mt-8 divide-y divide-border">{[["Ponto mais forte", score.strongest_pillar], ["Maior gargalo", score.bottleneck], ["Prioridade atual", score.priority], ["Nível de coerência", score.coherence_level]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 py-4 text-sm"><span className="text-muted-foreground">{label}</span><strong className="text-right">{value ?? "—"}</strong></div>)}</div><div className="mt-6 border-l border-primary pl-4"><p className="sim-kicker">Primeira recomendação</p><p className="mt-2">{score.recommendation}</p></div></div></div></main>;
}