import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CalendarDays, Check, MapPin, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/sim/AppShell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";

export const Route=createFileRoute("/_authenticated/experiences")({head:()=>({meta:[{title:"Experiences — Shape Is Money"},{name:"description",content:"Experiências privadas para membros Shape Is Money."},{property:"og:title",content:"Experiences — Shape Is Money"},{property:"og:description",content:"Encontros e experiências com acesso por interesse."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
function Page(){const[items,setItems]=useState<Tables<"member_experiences">[]>([]);const[interests,setInterests]=useState(new Set<string>());async function load(){const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const[e,i]=await Promise.all([supabase.from("member_experiences").select("*").eq("active",true).order("starts_at"),supabase.from("experience_interests").select("experience_id").eq("user_id",auth.user.id).neq("status","cancelled")]);setItems(e.data??[]);setInterests(new Set((i.data??[]).map(x=>x.experience_id)))}useEffect(()=>{void load()},[]);async function express(id:string){const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{error}=await supabase.from("experience_interests").upsert({experience_id:id,user_id:auth.user.id,status:"interested"},{onConflict:"experience_id,user_id"});if(error)toast.error(error.message);else{toast.success("Interesse registrado.");await load()}}return <AppShell><div className="mx-auto max-w-6xl px-5 py-10"><header className="border-b border-border pb-10"><p className="sim-kicker">Members · Experiences</p><h1 className="mt-4 text-6xl">Experiências privadas.</h1><p className="mt-4 max-w-2xl text-muted-foreground">Manifestar interesse não realiza compra nem garante vaga. A equipe confirma cada acesso.</p></header><div className="py-8">{items.map(item=><article key={item.id} className="grid gap-8 border-b border-border py-10 lg:grid-cols-[280px_1fr_auto] lg:items-center">{item.cover_url?<img src={item.cover_url} alt="" className="aspect-[4/3] w-full object-cover"/>:<div className="grid aspect-[4/3] place-items-center border border-border"><CalendarDays className="size-7 text-primary"/></div>}<div><p className="sim-kicker">{item.minimum_plan} access</p><h2 className="mt-3 text-4xl">{item.title}</h2><div className="mt-4 flex flex-wrap gap-5 text-xs text-muted-foreground">{item.starts_at&&<span><CalendarDays className="mr-2 inline size-3"/>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"long",timeStyle:"short"}).format(new Date(item.starts_at))}</span>}{item.location&&<span><MapPin className="mr-2 inline size-3"/>{item.location}</span>}{item.capacity&&<span><Users className="mr-2 inline size-3"/>{item.capacity} vagas</span>}</div><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">{item.description}</p></div><Button variant={interests.has(item.id)?"quiet":"gold"} disabled={interests.has(item.id)} onClick={()=>void express(item.id)}>{interests.has(item.id)?<><Check/>Interesse registrado</>:"Manifestar interesse"}</Button></article>)}{!items.length&&<p className="py-16 text-center text-muted-foreground">Nenhuma experiência com acesso aberto neste momento.</p>}</div></div></AppShell>}