import { useCallback, useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Check, Circle } from "lucide-react";
import { AppShell } from "@/components/sim/AppShell";
import { TeamConversation } from "@/components/sim/TeamConversation";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/_authenticated/habits")({head:()=>({meta:[{title:"Hábitos em construção — Shape Is Money"},{name:"description",content:"Compromissos mínimos que sustentam sua performance."},{property:"og:title",content:"Hábitos em construção — Shape Is Money"},{property:"og:description",content:"Acompanhe consistência com evidências reais."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page});
type Habit={id:string;title:string;description:string|null;pillar:string;target_frequency:number;period:string;current_streak:number;best_streak:number;habit_logs:{id:string;log_date:string;completed:boolean}[]};
const pillarLabels:Record<string,string>={construction:"Construção",capacity:"Capacidade",governance:"Governo",perception:"Percepção",execution:"Execução"};
function Page(){const[habits,setHabits]=useState<Habit[]>([]);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{data}=await supabase.from("client_habits").select("id,title,description,pillar,target_frequency,period,current_streak,best_streak,habit_logs(id,log_date,completed)").eq("client_id",auth.user.id).eq("status","active").order("created_at");setHabits((data??[])as Habit[]);setLoading(false)},[]);useEffect(()=>{void load()},[load]);const today=new Date().toLocaleDateString("en-CA");const completed=useMemo(()=>new Set(habits.filter(h=>h.habit_logs.some(log=>log.log_date===today&&log.completed)).map(h=>h.id)),[habits,today]);async function toggle(habit:Habit){const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const done=completed.has(habit.id);if(done)await supabase.from("habit_logs").delete().eq("habit_id",habit.id).eq("log_date",today);else await supabase.from("habit_logs").upsert({habit_id:habit.id,client_id:auth.user.id,log_date:today,completed:true},{onConflict:"habit_id,log_date"});await load()}if(loading)return <AppShell><div className="grid min-h-[70vh] place-items-center"><p className="sim-kicker">Abrindo hábitos</p></div></AppShell>;return <AppShell><div className="mx-auto max-w-5xl px-5 py-10"><p className="sim-kicker">Hábitos em construção</p><h1 className="mt-4 text-5xl">O mínimo que sustenta o todo.</h1><p className="mt-4 max-w-2xl text-muted-foreground">Registre somente o que foi realizado. A consistência atualiza sua leitura de performance.</p><div className="mt-10 divide-y divide-border border-y border-border">{habits.map(habit=>{const done=completed.has(habit.id);return <article key={habit.id} className="grid gap-5 py-7 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="sim-kicker">{pillarLabels[habit.pillar]??habit.pillar} · {habit.target_frequency}× por {habit.period==="daily"?"dia":"semana"}</p><h2 className="mt-2 text-3xl">{habit.title}</h2>{habit.description&&<p className="mt-2 text-sm text-muted-foreground">{habit.description}</p>}<p className="mt-3 text-xs text-muted-foreground">Sequência atual {habit.current_streak} · melhor {habit.best_streak}</p></div><Button variant={done?"gold":"quiet"} onClick={()=>void toggle(habit)}>{done?<Check/>:<Circle/>}{done?"Realizado hoje":"Marcar como feito"}</Button></article>})}{!habits.length&&<div className="py-14"><h2 className="text-3xl">Nenhum hábito ativo.</h2><p className="mt-3 text-muted-foreground">A equipe publicará hábitos quando houver evidência suficiente para uma recomendação.</p></div>}</div><div className="mt-12"><TeamConversation contextType="habit"/></div></div></AppShell>}