import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { AppShell } from "@/components/sim/AppShell";
import { LockedFeature } from "@/components/sim/LockedFeature";
import { useEntitlement } from "@/hooks/use-entitlement";

export const Route = createFileRoute("/_authenticated/nutrition")({ head: () => ({ meta: [{ title: "Nutrição — SIM OS" }, { name: "description", content: "Seu planejamento alimentar revisado pela equipe." }, { property: "og:title", content: "Nutrição — SIM OS" }, { property: "og:description", content: "Orientação alimentar para sustentar performance." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });
type Item = Tables<"nutrition_meal_items">;
type Meal = Tables<"nutrition_meals"> & { nutrition_meal_items: Item[] };
type Plan = Tables<"nutrition_plans"> & { nutrition_meals: Meal[] };
const value = (amount: number | null, suffix: string) => amount === null ? "—" : `${amount}${suffix}`;

function Page() {
  const entitlement = useEntitlement("can_access_nutrition");
  const [plan, setPlan] = useState<Plan | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const { data } = await supabase.from("nutrition_plans").select("*,nutrition_meals(*,nutrition_meal_items(*))").eq("user_id", auth.user.id).eq("status", "published").order("published_at", { ascending: false }).limit(1).maybeSingle(); setPlan(data as unknown as Plan | null); setLoading(false); })(); }, []);
  if (entitlement.loading || loading) return <AppShell><div className="grid min-h-[70vh] place-items-center"><p className="sim-kicker">Abrindo orientação</p></div></AppShell>;
  if (!entitlement.enabled) return <AppShell><div className="mx-auto max-w-4xl px-5 py-16"><LockedFeature title="Direção nutricional" description="Seu plano atual não inclui acompanhamento nutricional. Nenhuma meta será estimada sem orientação da equipe."/></div></AppShell>;
  if (!plan) return <AppShell><div className="mx-auto max-w-5xl px-5 py-16"><p className="sim-kicker">Nutrição</p><h1 className="mt-5 text-5xl">Seu plano nutricional está sendo preparado.</h1><p className="mt-4 max-w-2xl text-muted-foreground">A orientação aparecerá aqui somente depois da revisão e publicação pela equipe.</p></div></AppShell>;
  const meals = [...plan.nutrition_meals].sort((a,b)=>a.meal_order-b.meal_order);
  return <AppShell><div className="mx-auto max-w-6xl px-5 py-10"><header className="border-b border-border pb-9"><p className="sim-kicker">Nutrição · orientação revisada</p><h1 className="mt-4 text-5xl">{plan.title}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{plan.objective || "Planejamento alimentar publicado pela equipe."}</p></header><section className="grid grid-cols-2 border-b border-border sm:grid-cols-5">{[["Calorias",value(plan.calorie_target," kcal")],["Proteína",value(plan.protein_target," g")],["Carboidratos",value(plan.carbs_target," g")],["Gorduras",value(plan.fat_target," g")],["Água",value(plan.water_target_ml," ml")]].map(([label,amount])=><div key={label} className="border-b border-border py-6 sm:border-b-0 sm:border-r sm:px-5 first:pl-0 last:border-r-0"><p className="sim-kicker">{label}</p><p className="mt-3 font-display text-3xl">{amount}</p></div>)}</section><section className="py-10"><p className="sim-kicker">Seu plano</p><div className="mt-7 divide-y divide-border border-y border-border">{meals.map((meal)=><article key={meal.id} className="grid gap-5 py-7 md:grid-cols-[150px_1fr]"><div><p className="font-display text-3xl text-primary">{meal.suggested_time?.slice(0,5) || "—"}</p><h2 className="mt-2 text-xl">{meal.name}</h2></div><div><div className="space-y-3">{[...meal.nutrition_meal_items].sort((a,b)=>a.item_order-b.item_order).map((item)=><div key={item.id} className="grid gap-1 text-sm sm:grid-cols-[1fr_auto]"><p>{item.food_name} <span className="text-muted-foreground">{item.quantity !== null ? `· ${item.quantity} ${item.unit ?? ""}` : ""}</span></p><p className="text-xs text-muted-foreground">{item.calories !== null ? `${item.calories} kcal` : ""}{item.protein !== null ? ` · P ${item.protein}g` : ""}{item.carbs !== null ? ` · C ${item.carbs}g` : ""}{item.fat !== null ? ` · G ${item.fat}g` : ""}</p></div>)}</div>{meal.instructions&&<p className="mt-4 text-xs text-muted-foreground">{meal.instructions}</p>}</div></article>)}</div></section>{plan.notes&&<section className="border-y border-border bg-surface-coffee/35 px-6 py-8"><p className="sim-kicker">Orientação</p><p className="mt-4 max-w-3xl leading-7">{plan.notes}</p></section>}</div></AppShell>;
}