import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Check, Play, ShieldAlert } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/sim/AppShell";import{UsageTracker}from"@/components/sim/UsageTracker";
import { LockedFeature } from "@/components/sim/LockedFeature";
import { ProtocolTimeline } from "@/components/sim/ProtocolTimeline";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useEntitlement } from "@/hooks/use-entitlement";

export const Route = createFileRoute("/_authenticated/training")({ head: () => ({ meta: [{ title: "Treino — SIM OS" }, { name: "description", content: "Seu protocolo de construção e capacidade." }, { property: "og:title", content: "Treino — SIM OS" }, { property: "og:description", content: "Execute seu protocolo com clareza." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });
type Exercise = { id: string; sets: number; reps: string; rep_min:number|null; rep_max:number|null; initial_load: number | null; rest_seconds: number; target_effort_type:string; target_effort:number|null; target_rpe: number | null; notes: string | null; reason_for_inclusion:string|null; pain_rule:string|null; sequence: number; exercise_library: { name: string; muscle_group: string } | null };
type Workout = { id: string; name: string; estimated_minutes: number | null; notes: string | null; variant_type:string; workout_exercises: Exercise[] };
type Program = { id: string; title: string; objective: string | null; why_this_plan:string|null; workouts: Workout[] };
type Log = Record<string, { load: string; reps: string; rpe: string; pain:string; techniqueOk:boolean; completed: boolean }>;
function Page() { const entitlement = useEntitlement("can_access_training"); const [program, setProgram] = useState<Program | null>(null); const [protocolStatus, setProtocolStatus] = useState("data_received"); const [active, setActive] = useState<Workout | null>(null); const [sessionId, setSessionId] = useState<string | null>(null); const [startedAt, setStartedAt] = useState<Date | null>(null); const [log, setLog] = useState<Log>({}); const [sessionRpe,setSessionRpe]=useState("");const[comment,setComment]=useState(""); const [done, setDone] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const [programResult, protocol] = await Promise.all([supabase.from("workout_programs").select("id,title,objective,why_this_plan,workouts(id,name,estimated_minutes,notes,sequence,variant_type,workout_exercises(id,sets,reps,rep_min,rep_max,initial_load,rest_seconds,target_rpe,target_effort_type,target_effort,notes,reason_for_inclusion,pain_rule,sequence,exercise_library(name,muscle_group)))").eq("user_id", auth.user.id).eq("status", "published").order("published_at", { ascending: false }).limit(1).maybeSingle(), supabase.from("protocols").select("status").eq("user_id", auth.user.id).order("created_at", { ascending: false }).limit(1).maybeSingle()]); setProgram(programResult.data as unknown as Program | null); setProtocolStatus(protocol.data?.status ?? "data_received"); setLoading(false); })(); }, []);
  async function start(workout: Workout) { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const { data } = await supabase.from("workout_sessions").insert({ user_id: auth.user.id, workout_id: workout.id, exercise_log: [] }).select("id,started_at").single(); if (data) { await supabase.from("crm_events").insert({ user_id: auth.user.id, event_type: "workout.started", metadata: { workout_id: workout.id, session_id: data.id } }); setSessionId(data.id); setStartedAt(new Date(data.started_at)); setActive({ ...workout, workout_exercises: [...workout.workout_exercises].sort((a,b)=>a.sequence-b.sequence) }); } }
  async function persist(next: Log) { setLog(next); if (sessionId) await supabase.from("workout_sessions").update({ exercise_log: Object.entries(next).map(([exercise_id, values]) => ({ exercise_id, ...values })) }).eq("id", sessionId); }
  async function finish() { if (!sessionId || !active || !startedAt) return; const completed = active.workout_exercises.filter((exercise) => log[exercise.id]?.completed).length; const percent = active.workout_exercises.length ? Math.round(completed / active.workout_exercises.length * 100) : 0; const duration = Math.max(1, Math.round((Date.now() - startedAt.getTime()) / 60000)); const { data: auth } = await supabase.auth.getUser();if(!auth.user)return;const sessionPain=Math.max(0,...Object.values(log).map(item=>Number(item.pain)||0)); await supabase.from("workout_sessions").update({ status:"completed",completed_at: new Date().toISOString(), duration_minutes: duration, completion_percent: percent,session_rpe:sessionRpe?Number(sessionRpe):null,session_pain:sessionPain,client_comment:comment||null, exercise_log: Object.entries(log).map(([exercise_id, values]) => ({ exercise_id, ...values })) }).eq("id", sessionId);const setRows=active.workout_exercises.flatMap(exercise=>{const item=log[exercise.id];return item?.completed?[{session_id:sessionId,workout_exercise_id:exercise.id,user_id:auth.user.id,set_number:1,load:item.load?Number(item.load):null,reps:item.reps?Number(item.reps):null,effort:item.rpe?Number(item.rpe):null,effort_type:"RPE",technique_ok:item.techniqueOk,pain:item.pain?Number(item.pain):0}]:[]});if(setRows.length)await supabase.from("exercise_set_logs").upsert(setRows,{onConflict:"session_id,workout_exercise_id,set_number"});if(sessionPain>=4)await supabase.from("pain_reports").insert({user_id:auth.user.id,session_id:sessionId,location:"Relato durante sessão",intensity:sessionPain,classification:sessionPain>=8?"RED":"YELLOW"});await supabase.from("crm_events").insert({ user_id: auth.user.id, event_type: "workout.completed", metadata: { workout_id: active.id, completion_percent: percent } }); setDone(true); }
  if (entitlement.loading || loading) return <AppShell><UsageTracker module="training"/><div className="grid min-h-[70vh] place-items-center"><p className="sim-kicker">Carregando protocolo</p></div></AppShell>;
  if (!entitlement.enabled) return <AppShell><div className="mx-auto max-w-4xl px-5 py-16"><LockedFeature title="Treino orientado" description="Seu plano atual inclui o diagnóstico. O protocolo de treino é liberado nos planos com acompanhamento."/></div></AppShell>;
  if (!program) return <AppShell><div className="mx-auto max-w-5xl px-5 py-16"><p className="sim-kicker">Protocolo executivo</p><h1 className="mt-5 text-5xl">Seu protocolo está sendo construído.</h1><p className="mt-4 max-w-2xl text-muted-foreground">A equipe está organizando os dados recebidos antes de publicar sua direção.</p><ProtocolTimeline status={protocolStatus}/></div></AppShell>;
  if (done) return <AppShell><div className="grid min-h-[75vh] place-items-center px-5 text-center"><div><Check className="mx-auto size-10 text-primary"/><p className="sim-kicker mt-5">Execução registrada</p><h1 className="mt-4 text-5xl">Treino concluído.</h1><p className="mt-4 text-muted-foreground">Sua execução foi incorporada à carteira.</p></div></div></AppShell>;
  if (active) return <AppShell><div className="mx-auto max-w-4xl px-5 py-10"><p className="sim-kicker">Sessão em andamento · {active.variant_type.replaceAll("_"," ")}</p><h1 className="mt-4 text-5xl">{active.name}</h1><div className="mt-10 divide-y divide-border border-y border-border">{active.workout_exercises.map((exercise) => { const current = log[exercise.id] ?? { load: "", reps: "", rpe: "",pain:"",techniqueOk:true, completed: false }; const fields: Array<["load" | "reps" | "rpe"|"pain", string]> = [["load", "Carga"], ["reps", "Reps realizadas"], ["rpe", exercise.target_effort_type||"RPE"],["pain","Dor 0–10"]]; return <article key={exercise.id} className="py-6"><div className="flex items-start justify-between"><div><h2 className="text-lg">{exercise.exercise_library?.name ?? "Exercício"}</h2><p className="mt-1 text-xs text-muted-foreground">{exercise.sets} séries · {exercise.reps} reps · {exercise.rest_seconds}s · {exercise.target_effort_type} alvo {exercise.target_effort??exercise.target_rpe??"—"}</p>{exercise.reason_for_inclusion&&<p className="mt-3 max-w-2xl text-sm text-primary">Por que existe: {exercise.reason_for_inclusion}</p>}{exercise.pain_rule&&<p className="mt-2 flex gap-2 text-xs text-muted-foreground"><ShieldAlert className="size-4"/>{exercise.pain_rule}</p>}</div><Button size="icon" variant={current.completed ? "gold" : "quiet"} onClick={() => void persist({ ...log, [exercise.id]: { ...current, completed: !current.completed } })}><Check/></Button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{fields.map(([key, label]) => <label key={key}><span className="sim-kicker">{label}</span><Input className="mt-2" type="number" min={key==="pain"?0:undefined} max={key==="pain"?10:undefined} value={current[key]} onChange={(event) => void persist({ ...log, [exercise.id]: { ...current, [key]: event.target.value } })}/></label>)}</div><Button className="mt-3" variant={current.techniqueOk?"quiet":"gold"} onClick={()=>void persist({...log,[exercise.id]:{...current,techniqueOk:!current.techniqueOk}})}>Técnica {current.techniqueOk?"estável":"precisa de revisão"}</Button></article>; })}</div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Input type="number" min={1} max={10} value={sessionRpe} onChange={e=>setSessionRpe(e.target.value)} placeholder="RPE da sessão"/><Input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Comentário para a equipe"/></div><Button variant="gold" className="mt-4 h-12 w-full" onClick={finish}>Concluir treino</Button></div></AppShell>;
  return <AppShell><div className="mx-auto max-w-5xl px-5 py-10"><p className="sim-kicker">O que eu preciso fazer hoje?</p><h1 className="mt-4 text-5xl">{program.title}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{program.why_this_plan??program.objective??"Direção publicada pela equipe."}</p><div className="mt-6 flex gap-4 border-y border-border py-4 text-xs uppercase text-muted-foreground"><span>Treino publicado</span><span>·</span><span>Check-in semanal disponível</span></div><div className="mt-10 space-y-4">{[...program.workouts].sort((a,b) => a.name.localeCompare(b.name)).map((workout) => <article key={workout.id} className="sim-panel grid gap-5 p-6 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="sim-kicker">{workout.variant_type.replaceAll("_"," ")}</p><h2 className="mt-2 text-3xl">{workout.name}</h2><p className="mt-2 text-xs text-muted-foreground">{workout.workout_exercises.length} exercícios{workout.estimated_minutes ? ` · ${workout.estimated_minutes} minutos estimados` : ""}</p></div><Button variant="gold" onClick={() => void start(workout)}><Play/> Iniciar treino</Button></article>)}</div></div></AppShell>;
}