import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/sim/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { classifyAttention } from "@/lib/training-rules";

export const Route = createFileRoute("/_authenticated/weekly-review")({ head: () => ({ meta: [{ title: "Revisão semanal — SIM OS" }, { name: "description", content: "Consolide sua semana de performance." }, { property: "og:title", content: "Revisão semanal — SIM OS" }, { property: "og:description", content: "Uma revisão breve da sua execução." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });
const fields = [["nutrition", "Alimentação"], ["sleep", "Sono"], ["stress", "Estresse"], ["energy", "Energia"], ["productivity", "Produtividade"], ["focus", "Foco"], ["schedule_control", "Controle da agenda"], ["relationships", "Relacionamentos"], ["quality_time", "Tempo de qualidade"], ["professional_performance", "Performance profissional percebida"]] as const;
function weekStart() { const date = new Date(); const day = date.getDay(); date.setDate(date.getDate() - (day === 0 ? 6 : day - 1)); return date.toLocaleDateString("en-CA"); }
function Page() {
  const [values, setValues] = useState<Record<string, number>>({}); const [planned, setPlanned] = useState(0); const [completed, setCompleted] = useState(0); const [done, setDone] = useState(false);const[context,setContext]=useState({sleep_hours:"",pain:"",hydration:"",weight_kg:"",body_feeling:"",cardio:"",activity:"",worked:"",did_not_work:"",next_obstacle:""});
  useEffect(() => { void (async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const { data } = await supabase.from("weekly_reviews").select("*").eq("user_id", auth.user.id).eq("week_start", weekStart()).maybeSingle(); if (!data) return; setPlanned(data.planned_workouts); setCompleted(data.completed_workouts); setValues(Object.fromEntries(fields.flatMap(([key]) => data[key] === null ? [] : [[key, data[key]]])));setContext({sleep_hours:String(data.sleep_hours??""),pain:String(data.pain??""),hydration:String(data.hydration??""),weight_kg:String(data.weight_kg??""),body_feeling:data.body_feeling??"",cardio:data.cardio??"",activity:data.activity??"",worked:data.worked??"",did_not_work:data.did_not_work??"",next_obstacle:data.next_obstacle??""}); })(); }, []);
  async function save() { const { data } = await supabase.auth.getUser(); if (!data.user || fields.some(([key]) => values[key] === undefined)) return; const payload = Object.fromEntries(fields.map(([key]) => [key, values[key]]));const completionRate=planned?Math.round(completed/planned*100):100;const attention=classifyAttention({pain:Number(context.pain)||0,sleepQuality:values["sleep"]??3,energy:values["energy"]??3,stress:values["stress"]??3,completionRate,repeatedMisses:Math.max(0,planned-completed)});const decision=attention==="RED"?"HUMAN_REVIEW":attention==="YELLOW"?"MINOR_ADJUSTMENT":"CONTINUE"; const { error } = await supabase.from("weekly_reviews").upsert({ user_id: data.user.id, week_start: weekStart(), planned_workouts: planned, completed_workouts: completed, ...payload,sleep_hours:Number(context.sleep_hours)||null,pain:Number(context.pain)||0,hydration:Number(context.hydration)||null,weight_kg:Number(context.weight_kg)||null,body_feeling:context.body_feeling,cardio:context.cardio,activity:context.activity,worked:context.worked,did_not_work:context.did_not_work,next_obstacle:context.next_obstacle,attention_level:attention,decision_classification:decision }, { onConflict: "user_id,week_start" }); if (!error){await supabase.from("crm_events").insert({user_id:data.user.id,event_type:attention==="RED"?"checkin.red":attention==="YELLOW"?"checkin.yellow":"checkin.submitted",metadata:{week_start:weekStart(),decision}});setDone(true);} }
  const incomplete = fields.some(([key]) => values[key] === undefined)||Object.values(context).some(value=>value.trim()==="");
  return <AppShell><div className="mx-auto max-w-4xl px-5 py-10"><Button asChild variant="ghost" className="px-0"><Link to="/check-ins"><ArrowLeft/> Check-in diário</Link></Button><p className="sim-kicker mt-8">Revisão semanal · 22 sinais</p><h1 className="mt-4 text-5xl">Consolide a semana.</h1>{done ? <div className="mt-12 border-y border-border py-14 text-center"><Check className="mx-auto text-primary"/><h2 className="mt-4 text-3xl">Semana registrada.</h2><p className="mt-3 text-muted-foreground">Uma semana isolada informa a decisão; não recria seu treino.</p></div> : <><div className="mt-10 grid gap-5 sm:grid-cols-2"><label><span className="sim-kicker">Treinos previstos</span><Input className="mt-2" type="number" min={0} max={14} value={planned} onChange={(event)=>setPlanned(Number(event.target.value))}/></label><label><span className="sim-kicker">Treinos realizados</span><Input className="mt-2" type="number" min={0} max={14} value={completed} onChange={(event)=>setCompleted(Number(event.target.value))}/></label></div><div className="mt-10 divide-y divide-border border-y border-border">{fields.map(([key,label])=><div key={key} className="grid grid-cols-[1fr_auto] items-center gap-5 py-5"><span>{label}</span><div className="flex gap-1">{[1,2,3,4,5].map((number)=><Button key={number} size="icon" variant={values[key]===number?"gold":"quiet"} onClick={()=>setValues({...values,[key]:number})}>{number}</Button>)}</div></div>)}</div><div className="mt-10 grid gap-4 sm:grid-cols-2">{([...["sleep_hours","Horas de sono"],["pain","Dor 0–10"],["hydration","Hidratação 1–5"],["weight_kg","Peso atual"]] as Array<[keyof typeof context,string]>).map(([key,label])=><label key={key}><span className="sim-kicker">{label}</span><Input className="mt-2" type="number" value={context[key]} onChange={e=>setContext({...context,[key]:e.target.value})}/></label>)}</div><div className="mt-4 grid gap-4">{([...["body_feeling","Como seu corpo respondeu?"],["cardio","Como foi o cardio?"],["activity","Como foi sua atividade fora do treino?"],["worked","O que funcionou?"],["did_not_work","O que não funcionou?"],["next_obstacle","Qual é o próximo obstáculo?"]] as Array<[keyof typeof context,string]>).map(([key,label])=><label key={key}><span className="sim-kicker">{label}</span><Textarea className="mt-2 rounded-none" value={context[key]} onChange={e=>setContext({...context,[key]:e.target.value})}/></label>)}</div><Button variant="gold" className="mt-8 h-12 w-full" disabled={incomplete} onClick={save}>Registrar revisão</Button></>}</div></AppShell>;
}