import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/sim/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/_authenticated/weekly-review")({ head: () => ({ meta: [{ title: "Revisão semanal — SIM OS" }, { name: "description", content: "Consolide sua semana de performance." }, { property: "og:title", content: "Revisão semanal — SIM OS" }, { property: "og:description", content: "Uma revisão breve da sua execução." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Page });
const fields = [["nutrition", "Alimentação"], ["sleep", "Sono"], ["stress", "Estresse"], ["energy", "Energia"], ["productivity", "Produtividade"], ["focus", "Foco"], ["schedule_control", "Controle da agenda"], ["relationships", "Relacionamentos"], ["quality_time", "Tempo de qualidade"], ["professional_performance", "Performance profissional percebida"]] as const;
function weekStart() { const date = new Date(); const day = date.getDay(); date.setDate(date.getDate() - (day === 0 ? 6 : day - 1)); return date.toLocaleDateString("en-CA"); }
function Page() { const [values, setValues] = useState<Record<string, number>>({}); const [planned, setPlanned] = useState(0); const [completed, setCompleted] = useState(0); const [done, setDone] = useState(false); async function save() { const { data } = await supabase.auth.getUser(); if (!data.user) return; const payload = Object.fromEntries(fields.map(([key]) => [key, values[key] ?? 3])); const { error } = await supabase.from("weekly_reviews").upsert({ user_id: data.user.id, week_start: weekStart(), planned_workouts: planned, completed_workouts: completed, ...payload }, { onConflict: "user_id,week_start" }); if (!error) setDone(true); }
  return <AppShell><div className="mx-auto max-w-4xl px-5 py-10"><Button asChild variant="ghost" className="px-0"><Link to="/check-ins"><ArrowLeft/> Check-in diário</Link></Button><p className="sim-kicker mt-8">Revisão semanal</p><h1 className="mt-4 text-5xl">Consolide a semana.</h1>{done ? <div className="mt-12 border-y border-border py-14 text-center"><Check className="mx-auto text-primary"/><h2 className="mt-4 text-3xl">Semana registrada.</h2></div> : <><div className="mt-10 grid gap-5 sm:grid-cols-2"><label><span className="sim-kicker">Treinos previstos</span><Input className="mt-2" type="number" min={0} max={14} value={planned} onChange={(event) => setPlanned(Number(event.target.value))}/></label><label><span className="sim-kicker">Treinos realizados</span><Input className="mt-2" type="number" min={0} max={14} value={completed} onChange={(event) => setCompleted(Number(event.target.value))}/></label></div><div className="mt-10 divide-y divide-border border-y border-border">{fields.map(([key, label]) => <div key={key} className="grid grid-cols-[1fr_auto] items-center gap-5 py-5"><span>{label}</span><div className="flex gap-1">{[1,2,3,4,5].map((number) => <Button key={number} size="icon" variant={values[key] === number ? "gold" : "quiet"} onClick={() => setValues({ ...values, [key]: number })}>{number}</Button>)}</div></div>)}</div><Button variant="gold" className="mt-8 h-12 w-full" onClick={save}>Registrar revisão</Button></>}</div></AppShell>;
}