/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCheckInsRouteImport } from './routes/_authenticated/check-ins'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosisRouteImport } from './routes/_authenticated/diagnosis'
import { Route as AuthenticatedExperiencesRouteImport } from './routes/_authenticated/experiences'
import { Route as AuthenticatedFoodLogRouteImport } from './routes/_authenticated/food-log'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMoneyBrainRouteImport } from './routes/_authenticated/money-brain'
import { Route as AuthenticatedMonthlyReviewRouteImport } from './routes/_authenticated/monthly-review'
import { Route as AuthenticatedMyJourneyRouteImport } from './routes/_authenticated/my-journey'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerceptionLabRouteImport } from './routes/_authenticated/perception-lab'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSimSelectRouteImport } from './routes/_authenticated/sim-select'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedWeeklyReviewRouteImport } from './routes/_authenticated/weekly-review'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminExperiencesRouteImport } from './routes/_authenticated/admin.experiences'
import { Route as AuthenticatedAdminIntelligenceRouteImport } from './routes/_authenticated/admin.intelligence'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminMoneyBrainRouteImport } from './routes/_authenticated/admin.money-brain'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin.operations'
import { Route as AuthenticatedAdminPerceptionRouteImport } from './routes/_authenticated/admin.perception'
import { Route as AuthenticatedAdminRelationshipRouteImport } from './routes/_authenticated/admin.relationship'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSimSelectRouteImport } from './routes/_authenticated/admin.sim-select'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin.tasks'
import { Route as AuthenticatedMembersSlugRouteImport } from './routes/_authenticated/members.$slug'
import { Route as AuthenticatedTrainingAssessmentRouteImport } from './routes/_authenticated/training.assessment'
import { Route as AuthenticatedAdminRelationshipStudentIdRouteImport } from './routes/_authenticated/admin.relationship.$studentId'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated/admin.students.index'
import { Route as AuthenticatedAdminStudentsStudentIdRouteImport } from './routes/_authenticated/admin.students.$studentId'
import { Route as AuthenticatedAdminTrainingIndexRouteImport } from './routes/_authenticated/admin.training.index'
import { Route as AuthenticatedAdminTrainingStudentIdRouteImport } from './routes/_authenticated/admin.training.$studentId'
import { Route as AuthenticatedAdminTrainingExerciseImportRouteImport } from './routes/_authenticated/admin.training.exercise-import'
import { Route as AuthenticatedAdminTrainingExercisesRouteImport } from './routes/_authenticated/admin.training.exercises'
import { Route as AuthenticatedAdminTrainingKnowledgeRouteImport } from './routes/_authenticated/admin.training.knowledge'
import { Route as AuthenticatedAdminTrainingPhotoProtocolRouteImport } from './routes/_authenticated/admin.training.photo-protocol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckInsRoute = AuthenticatedCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosisRoute = AuthenticatedDiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperiencesRoute =
  AuthenticatedExperiencesRouteImport.update({
    id: '/experiences',
    path: '/experiences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodLogRoute = AuthenticatedFoodLogRouteImport.update({
  id: '/food-log',
  path: '/food-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyBrainRoute = AuthenticatedMoneyBrainRouteImport.update({
  id: '/money-brain',
  path: '/money-brain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthlyReviewRoute =
  AuthenticatedMonthlyReviewRouteImport.update({
    id: '/monthly-review',
    path: '/monthly-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyJourneyRoute = AuthenticatedMyJourneyRouteImport.update({
  id: '/my-journey',
  path: '/my-journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerceptionLabRoute =
  AuthenticatedPerceptionLabRouteImport.update({
    id: '/perception-lab',
    path: '/perception-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimSelectRoute = AuthenticatedSimSelectRouteImport.update({
  id: '/sim-select',
  path: '/sim-select',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeeklyReviewRoute =
  AuthenticatedWeeklyReviewRouteImport.update({
    id: '/weekly-review',
    path: '/weekly-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminExperiencesRoute =
  AuthenticatedAdminExperiencesRouteImport.update({
    id: '/admin/experiences',
    path: '/admin/experiences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntelligenceRoute =
  AuthenticatedAdminIntelligenceRouteImport.update({
    id: '/admin/intelligence',
    path: '/admin/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/admin/members',
    path: '/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMoneyBrainRoute =
  AuthenticatedAdminMoneyBrainRouteImport.update({
    id: '/admin/money-brain',
    path: '/admin/money-brain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/admin/operations',
    path: '/admin/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerceptionRoute =
  AuthenticatedAdminPerceptionRouteImport.update({
    id: '/admin/perception',
    path: '/admin/perception',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRelationshipRoute =
  AuthenticatedAdminRelationshipRouteImport.update({
    id: '/admin/relationship',
    path: '/admin/relationship',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSimSelectRoute =
  AuthenticatedAdminSimSelectRouteImport.update({
    id: '/admin/sim-select',
    path: '/admin/sim-select',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersSlugRoute =
  AuthenticatedMembersSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedTrainingAssessmentRoute =
  AuthenticatedTrainingAssessmentRouteImport.update({
    id: '/assessment',
    path: '/assessment',
    getParentRoute: () => AuthenticatedTrainingRoute,
  } as any)
const AuthenticatedAdminRelationshipStudentIdRoute =
  AuthenticatedAdminRelationshipStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedAdminRelationshipRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminStudentsStudentIdRoute =
  AuthenticatedAdminStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)
const AuthenticatedAdminTrainingIndexRoute =
  AuthenticatedAdminTrainingIndexRouteImport.update({
    id: '/admin/training/',
    path: '/admin/training/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingStudentIdRoute =
  AuthenticatedAdminTrainingStudentIdRouteImport.update({
    id: '/admin/training/$studentId',
    path: '/admin/training/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingExerciseImportRoute =
  AuthenticatedAdminTrainingExerciseImportRouteImport.update({
    id: '/admin/training/exercise-import',
    path: '/admin/training/exercise-import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingExercisesRoute =
  AuthenticatedAdminTrainingExercisesRouteImport.update({
    id: '/admin/training/exercises',
    path: '/admin/training/exercises',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingKnowledgeRoute =
  AuthenticatedAdminTrainingKnowledgeRouteImport.update({
    id: '/admin/training/knowledge',
    path: '/admin/training/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTrainingPhotoProtocolRoute =
  AuthenticatedAdminTrainingPhotoProtocolRouteImport.update({
    id: '/admin/training/photo-protocol',
    path: '/admin/training/photo-protocol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/check-ins': typeof AuthenticatedCheckInsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/experiences': typeof AuthenticatedExperiencesRoute
  '/food-log': typeof AuthenticatedFoodLogRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/money-brain': typeof AuthenticatedMoneyBrainRoute
  '/monthly-review': typeof AuthenticatedMonthlyReviewRoute
  '/my-journey': typeof AuthenticatedMyJourneyRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perception-lab': typeof AuthenticatedPerceptionLabRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sim-select': typeof AuthenticatedSimSelectRoute
  '/training': typeof AuthenticatedTrainingRouteWithChildren
  '/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/admin/experiences': typeof AuthenticatedAdminExperiencesRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/money-brain': typeof AuthenticatedAdminMoneyBrainRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/perception': typeof AuthenticatedAdminPerceptionRoute
  '/admin/relationship': typeof AuthenticatedAdminRelationshipRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sim-select': typeof AuthenticatedAdminSimSelectRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/members/$slug': typeof AuthenticatedMembersSlugRoute
  '/training/assessment': typeof AuthenticatedTrainingAssessmentRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/relationship/$studentId': typeof AuthenticatedAdminRelationshipStudentIdRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/admin/training/$studentId': typeof AuthenticatedAdminTrainingStudentIdRoute
  '/admin/training/exercise-import': typeof AuthenticatedAdminTrainingExerciseImportRoute
  '/admin/training/exercises': typeof AuthenticatedAdminTrainingExercisesRoute
  '/admin/training/knowledge': typeof AuthenticatedAdminTrainingKnowledgeRoute
  '/admin/training/photo-protocol': typeof AuthenticatedAdminTrainingPhotoProtocolRoute
  '/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/training/': typeof AuthenticatedAdminTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/check-ins': typeof AuthenticatedCheckInsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/experiences': typeof AuthenticatedExperiencesRoute
  '/food-log': typeof AuthenticatedFoodLogRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/money-brain': typeof AuthenticatedMoneyBrainRoute
  '/monthly-review': typeof AuthenticatedMonthlyReviewRoute
  '/my-journey': typeof AuthenticatedMyJourneyRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perception-lab': typeof AuthenticatedPerceptionLabRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sim-select': typeof AuthenticatedSimSelectRoute
  '/training': typeof AuthenticatedTrainingRouteWithChildren
  '/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/admin/experiences': typeof AuthenticatedAdminExperiencesRoute
  '/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/money-brain': typeof AuthenticatedAdminMoneyBrainRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/perception': typeof AuthenticatedAdminPerceptionRoute
  '/admin/relationship': typeof AuthenticatedAdminRelationshipRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sim-select': typeof AuthenticatedAdminSimSelectRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/members/$slug': typeof AuthenticatedMembersSlugRoute
  '/training/assessment': typeof AuthenticatedTrainingAssessmentRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/relationship/$studentId': typeof AuthenticatedAdminRelationshipStudentIdRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/admin/training/$studentId': typeof AuthenticatedAdminTrainingStudentIdRoute
  '/admin/training/exercise-import': typeof AuthenticatedAdminTrainingExerciseImportRoute
  '/admin/training/exercises': typeof AuthenticatedAdminTrainingExercisesRoute
  '/admin/training/knowledge': typeof AuthenticatedAdminTrainingKnowledgeRoute
  '/admin/training/photo-protocol': typeof AuthenticatedAdminTrainingPhotoProtocolRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/training': typeof AuthenticatedAdminTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/check-ins': typeof AuthenticatedCheckInsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/_authenticated/experiences': typeof AuthenticatedExperiencesRoute
  '/_authenticated/food-log': typeof AuthenticatedFoodLogRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/money-brain': typeof AuthenticatedMoneyBrainRoute
  '/_authenticated/monthly-review': typeof AuthenticatedMonthlyReviewRoute
  '/_authenticated/my-journey': typeof AuthenticatedMyJourneyRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perception-lab': typeof AuthenticatedPerceptionLabRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sim-select': typeof AuthenticatedSimSelectRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRouteWithChildren
  '/_authenticated/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/_authenticated/admin/experiences': typeof AuthenticatedAdminExperiencesRoute
  '/_authenticated/admin/intelligence': typeof AuthenticatedAdminIntelligenceRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/money-brain': typeof AuthenticatedAdminMoneyBrainRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/perception': typeof AuthenticatedAdminPerceptionRoute
  '/_authenticated/admin/relationship': typeof AuthenticatedAdminRelationshipRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sim-select': typeof AuthenticatedAdminSimSelectRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/members/$slug': typeof AuthenticatedMembersSlugRoute
  '/_authenticated/training/assessment': typeof AuthenticatedTrainingAssessmentRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/relationship/$studentId': typeof AuthenticatedAdminRelationshipStudentIdRoute
  '/_authenticated/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/_authenticated/admin/training/$studentId': typeof AuthenticatedAdminTrainingStudentIdRoute
  '/_authenticated/admin/training/exercise-import': typeof AuthenticatedAdminTrainingExerciseImportRoute
  '/_authenticated/admin/training/exercises': typeof AuthenticatedAdminTrainingExercisesRoute
  '/_authenticated/admin/training/knowledge': typeof AuthenticatedAdminTrainingKnowledgeRoute
  '/_authenticated/admin/training/photo-protocol': typeof AuthenticatedAdminTrainingPhotoProtocolRoute
  '/_authenticated/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/_authenticated/admin/training/': typeof AuthenticatedAdminTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/check-ins'
    | '/dashboard'
    | '/diagnosis'
    | '/experiences'
    | '/food-log'
    | '/members'
    | '/money-brain'
    | '/monthly-review'
    | '/my-journey'
    | '/network'
    | '/nutrition'
    | '/onboarding'
    | '/perception-lab'
    | '/performance'
    | '/profile'
    | '/sim-select'
    | '/training'
    | '/weekly-review'
    | '/admin/experiences'
    | '/admin/intelligence'
    | '/admin/members'
    | '/admin/money-brain'
    | '/admin/operations'
    | '/admin/perception'
    | '/admin/relationship'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sim-select'
    | '/admin/students'
    | '/admin/tasks'
    | '/members/$slug'
    | '/training/assessment'
    | '/admin/'
    | '/admin/relationship/$studentId'
    | '/admin/students/$studentId'
    | '/admin/training/$studentId'
    | '/admin/training/exercise-import'
    | '/admin/training/exercises'
    | '/admin/training/knowledge'
    | '/admin/training/photo-protocol'
    | '/admin/students/'
    | '/admin/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/check-ins'
    | '/dashboard'
    | '/diagnosis'
    | '/experiences'
    | '/food-log'
    | '/members'
    | '/money-brain'
    | '/monthly-review'
    | '/my-journey'
    | '/network'
    | '/nutrition'
    | '/onboarding'
    | '/perception-lab'
    | '/performance'
    | '/profile'
    | '/sim-select'
    | '/training'
    | '/weekly-review'
    | '/admin/experiences'
    | '/admin/intelligence'
    | '/admin/members'
    | '/admin/money-brain'
    | '/admin/operations'
    | '/admin/perception'
    | '/admin/relationship'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sim-select'
    | '/admin/tasks'
    | '/members/$slug'
    | '/training/assessment'
    | '/admin'
    | '/admin/relationship/$studentId'
    | '/admin/students/$studentId'
    | '/admin/training/$studentId'
    | '/admin/training/exercise-import'
    | '/admin/training/exercises'
    | '/admin/training/knowledge'
    | '/admin/training/photo-protocol'
    | '/admin/students'
    | '/admin/training'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/check-ins'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnosis'
    | '/_authenticated/experiences'
    | '/_authenticated/food-log'
    | '/_authenticated/members'
    | '/_authenticated/money-brain'
    | '/_authenticated/monthly-review'
    | '/_authenticated/my-journey'
    | '/_authenticated/network'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/perception-lab'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_authenticated/sim-select'
    | '/_authenticated/training'
    | '/_authenticated/weekly-review'
    | '/_authenticated/admin/experiences'
    | '/_authenticated/admin/intelligence'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/money-brain'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/perception'
    | '/_authenticated/admin/relationship'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sim-select'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/members/$slug'
    | '/_authenticated/training/assessment'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/relationship/$studentId'
    | '/_authenticated/admin/students/$studentId'
    | '/_authenticated/admin/training/$studentId'
    | '/_authenticated/admin/training/exercise-import'
    | '/_authenticated/admin/training/exercises'
    | '/_authenticated/admin/training/knowledge'
    | '/_authenticated/admin/training/photo-protocol'
    | '/_authenticated/admin/students/'
    | '/_authenticated/admin/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/check-ins': {
      id: '/_authenticated/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof AuthenticatedCheckInsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosis': {
      id: '/_authenticated/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof AuthenticatedDiagnosisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences': {
      id: '/_authenticated/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof AuthenticatedExperiencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food-log': {
      id: '/_authenticated/food-log'
      path: '/food-log'
      fullPath: '/food-log'
      preLoaderRoute: typeof AuthenticatedFoodLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money-brain': {
      id: '/_authenticated/money-brain'
      path: '/money-brain'
      fullPath: '/money-brain'
      preLoaderRoute: typeof AuthenticatedMoneyBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly-review': {
      id: '/_authenticated/monthly-review'
      path: '/monthly-review'
      fullPath: '/monthly-review'
      preLoaderRoute: typeof AuthenticatedMonthlyReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-journey': {
      id: '/_authenticated/my-journey'
      path: '/my-journey'
      fullPath: '/my-journey'
      preLoaderRoute: typeof AuthenticatedMyJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perception-lab': {
      id: '/_authenticated/perception-lab'
      path: '/perception-lab'
      fullPath: '/perception-lab'
      preLoaderRoute: typeof AuthenticatedPerceptionLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sim-select': {
      id: '/_authenticated/sim-select'
      path: '/sim-select'
      fullPath: '/sim-select'
      preLoaderRoute: typeof AuthenticatedSimSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weekly-review': {
      id: '/_authenticated/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof AuthenticatedWeeklyReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/experiences': {
      id: '/_authenticated/admin/experiences'
      path: '/admin/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AuthenticatedAdminExperiencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/intelligence': {
      id: '/_authenticated/admin/intelligence'
      path: '/admin/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/money-brain': {
      id: '/_authenticated/admin/money-brain'
      path: '/admin/money-brain'
      fullPath: '/admin/money-brain'
      preLoaderRoute: typeof AuthenticatedAdminMoneyBrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/perception': {
      id: '/_authenticated/admin/perception'
      path: '/admin/perception'
      fullPath: '/admin/perception'
      preLoaderRoute: typeof AuthenticatedAdminPerceptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/relationship': {
      id: '/_authenticated/admin/relationship'
      path: '/admin/relationship'
      fullPath: '/admin/relationship'
      preLoaderRoute: typeof AuthenticatedAdminRelationshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sim-select': {
      id: '/_authenticated/admin/sim-select'
      path: '/admin/sim-select'
      fullPath: '/admin/sim-select'
      preLoaderRoute: typeof AuthenticatedAdminSimSelectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/$slug': {
      id: '/_authenticated/members/$slug'
      path: '/$slug'
      fullPath: '/members/$slug'
      preLoaderRoute: typeof AuthenticatedMembersSlugRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/training/assessment': {
      id: '/_authenticated/training/assessment'
      path: '/assessment'
      fullPath: '/training/assessment'
      preLoaderRoute: typeof AuthenticatedTrainingAssessmentRouteImport
      parentRoute: typeof AuthenticatedTrainingRoute
    }
    '/_authenticated/admin/relationship/$studentId': {
      id: '/_authenticated/admin/relationship/$studentId'
      path: '/$studentId'
      fullPath: '/admin/relationship/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminRelationshipStudentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRelationshipRoute
    }
    '/_authenticated/admin/students/': {
      id: '/_authenticated/admin/students/'
      path: '/'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/students/$studentId': {
      id: '/_authenticated/admin/students/$studentId'
      path: '/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
    '/_authenticated/admin/training/': {
      id: '/_authenticated/admin/training/'
      path: '/admin/training'
      fullPath: '/admin/training/'
      preLoaderRoute: typeof AuthenticatedAdminTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training/$studentId': {
      id: '/_authenticated/admin/training/$studentId'
      path: '/admin/training/$studentId'
      fullPath: '/admin/training/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminTrainingStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training/exercise-import': {
      id: '/_authenticated/admin/training/exercise-import'
      path: '/admin/training/exercise-import'
      fullPath: '/admin/training/exercise-import'
      preLoaderRoute: typeof AuthenticatedAdminTrainingExerciseImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training/exercises': {
      id: '/_authenticated/admin/training/exercises'
      path: '/admin/training/exercises'
      fullPath: '/admin/training/exercises'
      preLoaderRoute: typeof AuthenticatedAdminTrainingExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training/knowledge': {
      id: '/_authenticated/admin/training/knowledge'
      path: '/admin/training/knowledge'
      fullPath: '/admin/training/knowledge'
      preLoaderRoute: typeof AuthenticatedAdminTrainingKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/training/photo-protocol': {
      id: '/_authenticated/admin/training/photo-protocol'
      path: '/admin/training/photo-protocol'
      fullPath: '/admin/training/photo-protocol'
      preLoaderRoute: typeof AuthenticatedAdminTrainingPhotoProtocolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersSlugRoute: typeof AuthenticatedMembersSlugRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersSlugRoute: AuthenticatedMembersSlugRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedTrainingRouteChildren {
  AuthenticatedTrainingAssessmentRoute: typeof AuthenticatedTrainingAssessmentRoute
}

const AuthenticatedTrainingRouteChildren: AuthenticatedTrainingRouteChildren = {
  AuthenticatedTrainingAssessmentRoute: AuthenticatedTrainingAssessmentRoute,
}

const AuthenticatedTrainingRouteWithChildren =
  AuthenticatedTrainingRoute._addFileChildren(
    AuthenticatedTrainingRouteChildren,
  )

interface AuthenticatedAdminRelationshipRouteChildren {
  AuthenticatedAdminRelationshipStudentIdRoute: typeof AuthenticatedAdminRelationshipStudentIdRoute
}

const AuthenticatedAdminRelationshipRouteChildren: AuthenticatedAdminRelationshipRouteChildren =
  {
    AuthenticatedAdminRelationshipStudentIdRoute:
      AuthenticatedAdminRelationshipStudentIdRoute,
  }

const AuthenticatedAdminRelationshipRouteWithChildren =
  AuthenticatedAdminRelationshipRoute._addFileChildren(
    AuthenticatedAdminRelationshipRouteChildren,
  )

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsStudentIdRoute: typeof AuthenticatedAdminStudentsStudentIdRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsStudentIdRoute:
      AuthenticatedAdminStudentsStudentIdRoute,
    AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckInsRoute: typeof AuthenticatedCheckInsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosisRoute: typeof AuthenticatedDiagnosisRoute
  AuthenticatedExperiencesRoute: typeof AuthenticatedExperiencesRoute
  AuthenticatedFoodLogRoute: typeof AuthenticatedFoodLogRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedMoneyBrainRoute: typeof AuthenticatedMoneyBrainRoute
  AuthenticatedMonthlyReviewRoute: typeof AuthenticatedMonthlyReviewRoute
  AuthenticatedMyJourneyRoute: typeof AuthenticatedMyJourneyRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerceptionLabRoute: typeof AuthenticatedPerceptionLabRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSimSelectRoute: typeof AuthenticatedSimSelectRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRouteWithChildren
  AuthenticatedWeeklyReviewRoute: typeof AuthenticatedWeeklyReviewRoute
  AuthenticatedAdminExperiencesRoute: typeof AuthenticatedAdminExperiencesRoute
  AuthenticatedAdminIntelligenceRoute: typeof AuthenticatedAdminIntelligenceRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminMoneyBrainRoute: typeof AuthenticatedAdminMoneyBrainRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminPerceptionRoute: typeof AuthenticatedAdminPerceptionRoute
  AuthenticatedAdminRelationshipRoute: typeof AuthenticatedAdminRelationshipRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSimSelectRoute: typeof AuthenticatedAdminSimSelectRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminTrainingStudentIdRoute: typeof AuthenticatedAdminTrainingStudentIdRoute
  AuthenticatedAdminTrainingExerciseImportRoute: typeof AuthenticatedAdminTrainingExerciseImportRoute
  AuthenticatedAdminTrainingExercisesRoute: typeof AuthenticatedAdminTrainingExercisesRoute
  AuthenticatedAdminTrainingKnowledgeRoute: typeof AuthenticatedAdminTrainingKnowledgeRoute
  AuthenticatedAdminTrainingPhotoProtocolRoute: typeof AuthenticatedAdminTrainingPhotoProtocolRoute
  AuthenticatedAdminTrainingIndexRoute: typeof AuthenticatedAdminTrainingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckInsRoute: AuthenticatedCheckInsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosisRoute: AuthenticatedDiagnosisRoute,
  AuthenticatedExperiencesRoute: AuthenticatedExperiencesRoute,
  AuthenticatedFoodLogRoute: AuthenticatedFoodLogRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedMoneyBrainRoute: AuthenticatedMoneyBrainRoute,
  AuthenticatedMonthlyReviewRoute: AuthenticatedMonthlyReviewRoute,
  AuthenticatedMyJourneyRoute: AuthenticatedMyJourneyRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerceptionLabRoute: AuthenticatedPerceptionLabRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSimSelectRoute: AuthenticatedSimSelectRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRouteWithChildren,
  AuthenticatedWeeklyReviewRoute: AuthenticatedWeeklyReviewRoute,
  AuthenticatedAdminExperiencesRoute: AuthenticatedAdminExperiencesRoute,
  AuthenticatedAdminIntelligenceRoute: AuthenticatedAdminIntelligenceRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminMoneyBrainRoute: AuthenticatedAdminMoneyBrainRoute,
  AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
  AuthenticatedAdminPerceptionRoute: AuthenticatedAdminPerceptionRoute,
  AuthenticatedAdminRelationshipRoute:
    AuthenticatedAdminRelationshipRouteWithChildren,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSimSelectRoute: AuthenticatedAdminSimSelectRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminTrainingStudentIdRoute:
    AuthenticatedAdminTrainingStudentIdRoute,
  AuthenticatedAdminTrainingExerciseImportRoute:
    AuthenticatedAdminTrainingExerciseImportRoute,
  AuthenticatedAdminTrainingExercisesRoute:
    AuthenticatedAdminTrainingExercisesRoute,
  AuthenticatedAdminTrainingKnowledgeRoute:
    AuthenticatedAdminTrainingKnowledgeRoute,
  AuthenticatedAdminTrainingPhotoProtocolRoute:
    AuthenticatedAdminTrainingPhotoProtocolRoute,
  AuthenticatedAdminTrainingIndexRoute: AuthenticatedAdminTrainingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
