/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCheckInsRouteImport } from './routes/_authenticated/check-ins'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosisRouteImport } from './routes/_authenticated/diagnosis'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedWeeklyReviewRouteImport } from './routes/_authenticated/weekly-review'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminStudentsStudentIdRouteImport } from './routes/_authenticated/admin.students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckInsRoute = AuthenticatedCheckInsRouteImport.update({
  id: '/check-ins',
  path: '/check-ins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosisRoute = AuthenticatedDiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeeklyReviewRoute =
  AuthenticatedWeeklyReviewRouteImport.update({
    id: '/weekly-review',
    path: '/weekly-review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStudentsStudentIdRoute =
  AuthenticatedAdminStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedAdminStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/check-ins': typeof AuthenticatedCheckInsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/check-ins': typeof AuthenticatedCheckInsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/check-ins': typeof AuthenticatedCheckInsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnosis': typeof AuthenticatedDiagnosisRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/weekly-review': typeof AuthenticatedWeeklyReviewRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/check-ins'
    | '/dashboard'
    | '/diagnosis'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/training'
    | '/weekly-review'
    | '/admin/students'
    | '/admin/'
    | '/admin/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/check-ins'
    | '/dashboard'
    | '/diagnosis'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/training'
    | '/weekly-review'
    | '/admin/students'
    | '/admin'
    | '/admin/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/check-ins'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnosis'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/training'
    | '/_authenticated/weekly-review'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/check-ins': {
      id: '/_authenticated/check-ins'
      path: '/check-ins'
      fullPath: '/check-ins'
      preLoaderRoute: typeof AuthenticatedCheckInsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosis': {
      id: '/_authenticated/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof AuthenticatedDiagnosisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/weekly-review': {
      id: '/_authenticated/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof AuthenticatedWeeklyReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students/$studentId': {
      id: '/_authenticated/admin/students/$studentId'
      path: '/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedAdminStudentsRoute
    }
  }
}

interface AuthenticatedAdminStudentsRouteChildren {
  AuthenticatedAdminStudentsStudentIdRoute: typeof AuthenticatedAdminStudentsStudentIdRoute
}

const AuthenticatedAdminStudentsRouteChildren: AuthenticatedAdminStudentsRouteChildren =
  {
    AuthenticatedAdminStudentsStudentIdRoute:
      AuthenticatedAdminStudentsStudentIdRoute,
  }

const AuthenticatedAdminStudentsRouteWithChildren =
  AuthenticatedAdminStudentsRoute._addFileChildren(
    AuthenticatedAdminStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckInsRoute: typeof AuthenticatedCheckInsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosisRoute: typeof AuthenticatedDiagnosisRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedWeeklyReviewRoute: typeof AuthenticatedWeeklyReviewRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckInsRoute: AuthenticatedCheckInsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosisRoute: AuthenticatedDiagnosisRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedWeeklyReviewRoute: AuthenticatedWeeklyReviewRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
